/**
 * CompassEats — Option B Blurb Import (Google Apps Script)
 * ========================================================
 * Writes blurb_short, blurb_long, AND chef onto matching venues-tab rows by slug.
 * Now covers the original 30 marquee venues PLUS the first 10 Tier-1 three-star
 * venues from the sourcing pipeline. Safe to re-run (idempotent).
 *
 * RUN ORDER: reshape -> mergeDuplicateVenues -> importBlurbsFromDrive (bulk) ->
 *            clearWrongCityBlurbs -> importOptionB (THIS) -> generateCitiesTab -> publish
 *
 * UPDATED June 11, 2026: removed the eight "-2" duplicate entries (steirereck-2,
 * noma-2, the-french-laundry-2, arpege-2, schloss-schauenstein-2, hof-van-cleve-2,
 * astrance-2, restaurant-quique-dacosta-2) — those duplicate venue rows are now
 * collapsed by mergeDuplicateVenues, so only the base slugs exist. Expect 40 / 40.
 */

function importOptionB() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName('venues');
  if (!sheet) throw new Error('No "venues" tab. Run reshapeCompassEats first.');

  var data = sheet.getDataRange().getValues();
  var headers = data[0];
  var col = {};
  for (var i = 0; i < headers.length; i++) col[headers[i]] = i;
  ['slug', 'blurb_short', 'blurb_long', 'chef'].forEach(function (c) {
    if (col[c] === undefined) throw new Error('venues tab missing column: ' + c);
  });

  var rowOf = {};
  for (var r = 1; r < data.length; r++) {
    var slug = String(data[r][col['slug']]).trim();
    if (slug) rowOf[slug] = r;
  }

  // [slug, chef, blurb_short, blurb_long]
  var OPTION_B = [
    ['steirereck', 'Heinz Reitbauer', 'Vienna\'s most quietly radical kitchen, tucked into a glass pavilion in the middle of the Stadtpark.', 'Chef Heinz Reitbauer runs Steirereck with a devotion to provenance that borders on the unreasonable — herbs off the roof, produce from the restaurant\'s own farm, citrus from a nearby imperial orangery. It\'s been known for years for dishes like char cooked in beeswax, and the bread and cheese trolley has a reputation that travels well past Austria. If you\'ve got one evening in Vienna for something special, this is where to spend it: three Michelin stars, a steady spot on the World\'s 50 Best — go hungry and let them lead.'],
    ['mugaritz', 'Andoni Luis Aduriz', 'Just outside San Sebastián, one of the world\'s ten best restaurants — and one of its most stubbornly experimental.', 'Mugaritz is less a restaurant than an open question about what dinner can be. Chef Andoni Luis Aduriz builds a long, ever-shifting tasting menu — a fair amount of it eaten with your hands — and there\'s a glossary on the table he wrote with his staff and even past guests, which tells you how much he enjoys bending the form. Expect conceptual, genuinely surprising plates from a two-Michelin-star kitchen that\'s held its place in the World\'s 50 Best top ten for years. Come ready to go along with it rather than order from it — that\'s the fun.'],
    ['noma', 'René Redzepi', 'The Copenhagen restaurant that rewrote the rules — New Nordic cooking started here, and the world followed.', 'It\'s genuinely hard to picture the last twenty years of food without it. When Chef René Redzepi opened Noma in a Copenhagen warehouse in 2003, he set out to prove that Nordic ingredients — not foie gras, not caviar — could carry cooking of the very highest order, and the cook-by-the-season idea that the entire restaurant world now takes for granted spread out from this room. He threw out the white tablecloths and the stiff service, too, and had the cooks themselves carry plates to the table. Five turns at No.1 on the World\'s 50 Best across two incarnations, three Michelin stars. If you only ever build one trip around a restaurant, it\'s a defensible choice.'],
    ['the-french-laundry', 'Thomas Keller', 'Chef Thomas Keller\'s Napa landmark — and the kitchen that quietly trained a generation of America\'s best.', 'Grant Achatz, René Redzepi, Corey Lee — all passed through this Yountville kitchen before going on to define their own. For decades it\'s been one of the hardest bookings in America, and the cooking earns it: exacting French technique, pristine Napa Valley ingredients, a long tasting menu served in a room where someone has clearly agonized over every detail down to the height of the counters. Three Michelin stars and two years atop the World\'s 50 Best. The reservation is the hard part; the rest takes care of itself.'],
    ['alinea', 'Grant Achatz', 'Chicago\'s temple of modernist cooking, where dinner is staged as much as it\'s plated.', 'Chef Grant Achatz turned dinner into performance art when he opened Alinea in Lincoln Park in 2005, and it still sets the pace for American modernist cooking. Scented vapors, tableside flourishes, an edible helium balloon, a dessert painted straight onto the table in front of you — you\'re part of the show as much as the staff are. Two Michelin stars and a long run on the World\'s 50 Best back up what the room already makes clear. Go for the spectacle; stay for the fact that it\'s also, quietly, extraordinary food.'],
    ['piazza-duomo', 'Enrico Crippa', 'Behind a famous red door in Alba, a soft-pink room serving some of Piedmont\'s most personal cooking.', 'Up the stair, past a Francesco Clemente fresco, Chef Enrico Crippa builds menus that turn almost entirely on the plant world — vegetables, flowers, and herbs, much of it from the restaurant\'s own farm and picked the same day. Come in autumn and the Langhe\'s white truffle takes over; the wine list runs to several volumes and is reason enough to make the trip on its own. Three Michelin stars and a long stay on the World\'s 50 Best. Worth the detour into truffle country.'],
    ['arpege', 'Alain Passard', 'Chef Alain Passard\'s Paris flagship, where vegetables from his own gardens are treated like royalty.', 'Chef Passard still cooks here most days, more than three decades after buying the place from his mentor — which already sets it apart from most rooms at this level. Vegetables arrive each morning from his three kitchen gardens in the French countryside and get turned into some of the most precise, beautiful plates in the city; he\'s the rare three-star chef who\'d rather talk about fruit and flowers than foie gras. There\'s still meat and fish on the menu, but the garden is unmistakably the star. Three Michelin stars held since 1996, and a leap into the World\'s 50 Best top ten. Not cheap, and not trying to be.'],
    ['le-calandr', 'Massimiliano Alajmo; Raffaele Alajmo', 'In small-town Padua country, the Alajmo brothers turned the family restaurant into one of Italy\'s defining tables.', 'Chef Massimiliano Alajmo cooks here alongside his brother Raffaele, who runs the room — they took over from their parents in 1994 and have since built it into the heart of a group spanning a dozen restaurants across three countries. The setting is pared-back and quietly considered, down to the porcelain the brothers designed themselves, and Max\'s cooking sits somewhere between comfort and mischief: dishes like the Cappuccino Murrina, a nod to Venetian glassblowing in cuttlefish and sea urchin, have been around long enough to count as icons. Three Michelin stars and a steady place on the World\'s 50 Best. Worth the short hop from Padua.'],
    ['arzak', 'Elena Arzak; Juan Mari Arzak', 'A century-old San Sebastián institution where the Arzak family has been quietly rewriting Basque cooking for generations.', 'Chef Juan Mari Arzak earned the restaurant\'s first Michelin star in 1974, and his daughter Chef Elena Arzak now runs the kitchen in the same family mansion the Arzaks have held since 1897 — a rare bit of culinary dynasty that mostly only Spain seems to produce. The cooking pairs deep Basque tradition with restless experimentation, much of it worked out in their in-house laboratory and a "flavour workbench" of more than a thousand ingredients. The menu is built to keep changing, so you go for the invention as much as any one dish, and the wine list runs to a genuinely absurd few thousand bottles. Three Michelin stars, half a century in the guide, and a long stay on the World\'s 50 Best.'],
    ['le-bernardin', 'Eric Ripert', 'Chef Eric Ripert\'s Midtown temple to seafood, and one of New York\'s most quintessential rooms.', 'Nearly everything here is in service of balance — between simplicity and refinement, French foundation and global reach — and Chef Eric Ripert has held that line for over three decades. The menu tells you the philosophy before the food does: it\'s divided into Almost Raw, Barely Touched, and Lightly Cooked, an entire worldview about not getting in the seafood\'s way. There\'s a generous à la carte rather than a forced march through a tasting menu, which makes it the rare room at this level you can drop into on your own terms. Three Michelin stars and a regular on the World\'s 50 Best. Dress up — everyone else will have.'],
    ['narisawa', 'Yoshihiro Narisawa', 'Tokyo\'s most thoughtful kitchen, where Japan\'s rural landscapes become the menu.', 'Chef Yoshihiro Narisawa cooks to a philosophy he calls innovative satoyama cuisine — built around Japan\'s rural hill-and-foothill country and the old idea of living in step with it. In practice that means deep ties to Japan\'s foraging and farming communities, native ingredients turned through European technique, even lacquerware and washi paper in the room. It was the very first winner of Asia\'s 50 Best Sustainable Restaurant award back in 2013, long before sustainability was a dining buzzword. Two Michelin stars and a fixture in the World\'s 50 Best top tier. Come curious.'],
    ['el-celler-de-can-roca', 'Joan Roca; Josep Roca; Jordi Roca', 'Three Roca brothers, one restaurant in Girona, and two turns as the best in the world.', 'The setup is the secret: Chef Joan Roca runs the savory kitchen, his brother Josep the wine, and Jordi the desserts — they call themselves an equilateral triangle, and four decades in, the geometry holds. The cooking is built on memory and travel and a real environmental conscience, beginning with a run of appetizers that nod to their own greatest hits. It\'s twice been No.1 on the World\'s 50 Best and a top-five mainstay since 2009, so tables are coveted — bookings open at midnight on the 1st, eleven months out, and go fast. Three Michelin stars. Mark your calendar and plan the trip around the table you land.'],
    ['d-o-m', 'Alex Atala', 'Chef Alex Atala\'s São Paulo landmark — a tasting menu that travels to the far reaches of the Amazon.', 'Atala is Brazil\'s most internationally known chef, and D.O.M. is where he makes his case: a tasting menu redesigned every year, built on deep research into native Amazonian ingredients and Brazilian folklore. Expect things you\'ve likely never eaten — priprioca root, tucupi, jambu — handled with real technique rather than novelty. The charming counter-move is at lunch, where the long-running Executive Menu serves a perfected version of Brazil\'s everyday rice and beans, reportedly Chef Atala\'s own favorite thing on offer. Two Michelin stars and years on Latin America\'s 50 Best. Go in with an open mind and you\'ll leave with a longer list of ingredients you love.'],
    ['schloss-schauenstein', 'Andreas Caminada', 'A 26-year-old took over an empty Swiss castle in 2003 — two decades on, it\'s one of the Alps\' great tables.', 'Chef Andreas Caminada cooks inside an honest-to-goodness castle at the foot of Piz Beverin, and there are eleven rooms upstairs if you want to make a real night of it. He builds the menu almost entirely out of Graubünden — a lot of it from the restaurant\'s own garden — instead of reaching for the usual luxury suspects, so the food tastes like the place you\'re sitting in. It\'s wood-clad and warm, big on foraging, and even the no-and-low pairing is something they clearly sweated over. Three Michelin stars and a steady spot on the World\'s 50 Best. Remote, yes — that\'s rather the point.'],
    ['pujol', 'Enrique Olvera', 'Chef Enrique Olvera\'s Mexico City landmark, where ancient tradition and invention sit at the same table.', 'Olvera has done as much as anyone alive to carry Mexican cooking onto the world stage without ever cutting it loose from roots that go back thousands of years — and Pujol, now twenty-five-plus years in, is where it all started. The seasonal tasting menu is the heart of it, but the thing a lot of people come for is the taco omakase, which shares a name with street food and almost nothing else. Whatever you do, don\'t skip the mole madre — a sauce they\'ve kept going and aged for well over a thousand days. Two Michelin stars and a long run on the World\'s 50 Best. Come hungry, come curious.'],
    ['hof-van-cleve', 'Floris Van der Veken; Peter Goossens', 'A Belgian farmhouse that\'s been one of the country\'s defining kitchens for over three decades.', 'Don\'t let the farmhouse fool you — inside is one of Belgium\'s most carefully considered dining rooms, right down to the custom cutlery and the clipped topiary. Chef Peter Goossens ran it from 1987 until handing the keys to Chef Floris Van der Veken in 2022, and the same obsession carries on: Belgian produce, global technique, and as much care lavished on a humble leek as on a noble turbot. Leave room, because the dessert trolley and the cheese board are legends in their own right. Two Michelin stars and a longtime fixture on the World\'s 50 Best. Worth the drive into the Flemish countryside.'],
    ['osteria-francescana', 'Massimo Bottura', 'Modena\'s temple to storytelling on a plate — twice the best restaurant in the world.', 'Chef Massimo Bottura took the Italian dishes everyone thinks they know and turned them into something closer to storytelling you can eat — a lemon tart named for the moment one got dropped, a love letter to the crunchy corner of nonna\'s lasagna, a "Five Ages of Parmigiano Reggiano" that\'s really five textures of one cheese. It nearly didn\'t make it: when it opened in 1995, locals were not at all sure about a man rethinking a cuisine this sacred. He stuck with it, twice landed at No.1 on the World\'s 50 Best, and hung contemporary art all over the dining room while he was at it. Three Michelin stars. One of the genuinely few places that changed how Italy cooks.'],
    ['pierre-gagnaire', 'Pierre Gagnaire', 'Chef Pierre Gagnaire\'s Paris flagship — three-star cooking with a poet\'s playfulness and a jazz musician\'s restlessness.', 'Gagnaire grew up in his family\'s Michelin-starred kitchen and has never once been interested in standing still. The menu reads like poetry, and the food turns up as little "satellite" portions sent into orbit rather than neat single plates — try to name his one emblematic dish and you\'ll give up, which is exactly how he likes it. A jazz and contemporary-art obsessive, he reinvents constantly; the room is quiet and understated, anchored by a sweeping charcoal mural. Three stars since 1996 and a longtime name on the World\'s 50 Best. Adventurous, generous, and worth the splurge.'],
    ['quintonil', 'Jorge Vallejo; Alejandra Flores', 'Named for a wild Mexican herb, Chef Jorge Vallejo\'s Mexico City kitchen turns the country\'s pantry into quiet art.', 'Chef Vallejo is out gathering ingredients every single day — local gardens, orchards, the length of Mexico\'s astonishing pantry — and it shows up on the plate as some of the prettiest food you\'ll come across, a leafy little bouquet where a tamale should be, flowers ringing a pool of mole. The room\'s stylish and genuinely relaxed, run out front by his wife Alejandra Flores, and the all-Mexican wine pairing changes constantly and is well worth a yes. Two Michelin stars and a regular near the top of the World\'s 50 Best. A bright, big-hearted case for modern Mexican cooking.'],
    ['geranium', 'Rasmus Kofoed; Søren Ledet', 'On the eighth floor above Copenhagen\'s football stadium, an unlikely setting for one of the world\'s very best.', 'Take the lift up Parken Stadium — yes, the football stadium — to the eighth floor, and you\'ll find Chef Rasmus Kofoed\'s Geranium, the first Danish restaurant ever to hold three Michelin stars, with huge windows over the park and a peek at the pitch below. Kofoed cooks with a precision that\'s honestly a little absurd, and the plates are some of the prettiest you\'ll see anywhere; he dropped meat entirely in 2022, so the long "Universe" menu runs on Scandinavian seafood and biodynamic vegetables and somehow never feels like it\'s missing a thing. His partner Søren Ledet runs a famously warm room and a drinks list to match, down to a juice pairing that\'s no afterthought. Topped the World\'s 50 Best and landed in its hall of fame. Worth every floor of the climb.'],
    ['restaurant-mirazur', 'Mauro Colagreco', 'Chef Mauro Colagreco\'s restaurant on the French-Italian border, with the sea below and the gardens running the menu.', 'Tucked onto the coast right where France meets Italy, Mirazur has the kind of Mediterranean view that would carry a lesser restaurant on its own — but Chef Mauro Colagreco isn\'t a coast-on-the-view sort. He runs the whole place by the lunar calendar now, harvesting from his own terraced gardens and building daily menus around nature itself: roots, leaves, flowers, fruit. The cooking is flawless but never fussy — big, harmonious flavors you don\'t need a decoder ring for. It topped the World\'s 50 Best, became the first restaurant anywhere to go fully plastic-free, and even bought a local bakery to make its own bread. Three Michelin stars. Go for the food; the view is just showing off.'],
    ['daniel', 'Daniel Boulud', 'Chef Daniel Boulud\'s Upper East Side flagship — old-world French grandeur, going strong for three decades.', 'Chef Boulud started cooking at fourteen and still lights up behind the stoves of his Upper East Side room, which has been the place for big deals and bigger occasions since 1993. He trained under a who\'s-who of French legends and brought that elegant, old-world style to New York whole — updated classics with his thumbprint on every one. If you can swing it, the Canard à la Presse is a genuine bit of theater (you order it a day ahead, they roast the duck and press the juices tableside for the sauce), but there are prix-fixe and vegetarian routes too if you\'d rather keep it simpler. One Michelin star and a longtime World\'s 50 Best name. The kind of grand New York night that doesn\'t really exist anywhere else.'],
    ['maido', 'Mitsuharu Tsumura', 'Chef Mitsuharu Tsumura\'s Lima landmark — Nikkei cooking, Japan and Peru on one plate, recently crowned the world\'s best.', '"Maido" is the greeting you\'ll hear the second you walk in, and it sets the tone for the whole thing. Chef Mitsuharu Tsumura — born in Lima, trained in Osaka — has spent fifteen-plus years here doing more than maybe anyone to put Nikkei cooking, the Japanese-Peruvian crossover, on the world map. The long tasting menu reaches deeper into the Amazon every year, with things like sustainable paiche "ham" and squid ramen turning up among the courses. It\'s been named the best restaurant in South America and, in 2025, the World\'s Best Restaurant outright. Come ready to eat your way between two cultures at once.'],
    ['central', 'Virgilio Martínez; Pía León', 'Chef Virgilio Martínez and Pía León\'s Lima landmark — a menu that climbs Peru by altitude, and the first South American restaurant ever named world\'s best.', 'No one else builds a menu quite like this: Chef Virgilio Martínez and his wife and co-chef Pía León take you up through Peru by elevation, one course at a time, from shellfish pulled below sea level to things that only grow high in the Andes. They\'re a little obsessed — Martínez\'s sister runs a whole team that roams the country hunting down ingredients most people have never heard of, then they figure out how to put them on a plate. There\'s a restaurant in the mountains near Cusco and another in Tokyo now, but Central in Lima\'s Barranco is the heart of it. In 2023 it became the first South American restaurant ever named the World\'s Best, and it pretty much redrew the map doing it. Worth crossing the world for.'],
    ['per-se', 'Thomas Keller', 'Chef Thomas Keller\'s New York counterpart to The French Laundry, with Central Park laid out below.', 'There\'s no bad seat at Per Se — every table looks out over Central Park like it\'s your own backyard. It\'s Chef Thomas Keller\'s New York companion to The French Laundry, and it runs on the same exacting logic: two nine-course tasting menus daily (one all-vegetable), choreographed so precisely that no single ingredient ever repeats across the meal. "Oysters and Pearls" and the big dessert finale are the dependable bookends; everything between is a quiet master class in confidence. Three Michelin stars, a 2,000-bottle cellar, and Keller\'s fingerprints on every detail. The New York archetype of American fine dining.'],
    ['asador-etxebarri', 'Bittor Arginzoniz', 'Chef Bittor Arginzoniz\'s temple to fire, deep in the Basque hills — where everything passes over flame.', 'People make a genuine pilgrimage out to this restored country house at the foot of Mt Anboto, and it\'s all for one thing: Chef Bittor Arginzoniz\'s mastery of fire. He cooks over different woods, on grills and pulleys he built himself, with a control over flame that\'s reshaped how a whole generation of cooks thinks about grilling. Everything\'s been kissed by it — Palamós prawns, his own chorizo, the legendary aged beef chop, even the milk ice cream with beetroot at the end. The room is proudly plain; the cooking does all the talking. One Michelin star and a World\'s 50 Best regular, about an hour out of Bilbao. Book months ahead — it\'s worth the wait and then some.'],
    ['astrance', 'Pascal Barbot', 'Chef Pascal Barbot\'s Paris kitchen, set in the legendary room where Robuchon once made his name.', 'There\'s real history in these walls — this is where Joël Robuchon built his reputation at Jamin — and Chef Pascal Barbot, with partner Christophe Rohat out front, has made the space his own while quietly tipping a hat to the great chef. Barbot cooks with an undimmed obsession for produce and a real love of Asian and plant-forward ideas, and longtime fans will be glad his famous button-mushroom and foie gras millefeuille is still very much on the menu. There\'s a stunning glass wine cellar, and a maître d\' who\'ll find you the rare bottle you didn\'t know you wanted. One Michelin star and a longtime presence on the World\'s 50 Best. Quietly one of Paris\'s best.'],
    ['borago', 'Rodolfo Guzmán', 'Chef Rodolfo Guzmán\'s Santiago kitchen, built entirely from Chile\'s wild edges.', 'Boragó is Chef Rodolfo Guzmán\'s deep dive into what Chile actually tastes like — the "Endémica" menu shifts with whatever turns up at the door, sourced from 200-odd tiny producers and foragers stretched from Patagonia to the Atacama, plus the restaurant\'s own biodynamic farm half an hour away. Dinner runs a dozen-plus courses, each one explained by where its ingredients came from, and the plating has a sense of mischief — ice cream that looks like a mushroom on a leaf, a dish styled after a Van Gogh sunflower. A longtime fixture near the top of Latin America\'s 50 Best. A real taste of a country, not just a meal.'],
    ['vendome', 'Joachim Wissler; Dennis Kuckuck', 'A destination kitchen in a castle hotel outside Cologne, long at the front of modern German cooking.', 'Vendôme sits inside the grand Schloss Bensberg hotel just outside Cologne, and it made its name under Chef Joachim Wissler — one of the people who basically dragged German fine dining into its modern era, taking the country\'s traditional food and running it through global ingredients and ideas. His longtime sous-chef Chef Dennis Kuckuck has taken over the stoves and hasn\'t let the standard slip an inch: French classics with a modern edge, everything clean and balanced and built to make you pay attention. Both menus come with or without meat, in five or seven courses, and the alcohol-free pairing is as considered as the wine list. Two Michelin stars. And since you\'re already in a castle, you may as well stay the night.'],
    ['restaurant-quique-dacosta', 'Quique Dacosta', 'Chef Quique Dacosta\'s Dénia restaurant, where the tasting menu is treated as an art form in its own right.', 'Chef Quique Dacosta walked in as a 17-year-old in 1989, bought the place in 1999, and put his own name over the door in 2009 — and it shows, because the cooking is unmistakably personal. He rebuilds the menu almost completely every year, treating a meal as something closer to art than dinner; one recent menu, "Octavo," cheekily argues cooking deserves a place alongside the seven classical fine arts. The inspiration keeps circling back to the Mediterranean, and the whole thing is built to lodge in your memory even as it vanishes on the plate. Three Michelin stars and a longtime World\'s 50 Best name. Go when you\'re in the mood to be surprised.'],
    ['azurmendi-jatetxea', 'Eneko Atxa', 'In the hills outside Bilbao, Chef Eneko Atxa\'s glass-walled temple to sustainable Basque cooking.', 'Chef Eneko Atxa was one of the youngest chefs ever to earn a third Michelin star, and he did it at Azurmendi — his first restaurant, opened in 2005 when he was in his twenties. The building is the first thing people talk about: a bioclimatic glass structure built into a Larrabetzu hillside, with a rooftop greenhouse, a seed bank for indigenous Basque species, and geothermal and solar systems woven through it. The long Adarrak tasting menu starts up in that greenhouse, where you see where the meal begins, and runs through dishes like his famous truffled egg "cooked inside out." It won the World\'s 50 Best Sustainable Restaurant award back in 2014, long before that was a fashionable thing to chase, and has climbed as high as No. 14 on the main list. Three Michelin stars. Worth the trip out from Bilbao.'],
    ['azabu-kadowaki', 'Toshiya Kadowaki', 'A six-seat Tokyo counter where Chef Toshiya Kadowaki has turned truffle rice into a pilgrimage.', 'Chef Toshiya Kadowaki opened this Azabu-Juban restaurant in 2000, earned two Michelin stars in 2010, and was bumped to three in 2020 — and yet the room has stayed tiny on purpose, just six seats at the counter and a low-ceilinged private room built to feel like a tearoom. The cooking is kaiseki at heart but threaded with Western ingredients and technique, the kind of quiet East-meets-West that reveals itself course by course. The thing people travel for is the truffle rice: a clay pot of hot rice buried under generous shavings of black truffle, served near the end of the meal and spoken about long after. Three Michelin stars, in a space that seats fewer people than most kitchens employ. Book well ahead.'],
    ['alleno', 'Yannick Alléno', 'Chef Yannick Alléno\'s flagship inside the Pavillon Ledoyen, where sauce is treated as the whole point.', 'Chef Yannick Alléno took over the historic Pavillon Ledoyen on the Champs-Élysées in 2014, opened his eponymous restaurant on its top floor, and had three Michelin stars seven months later. The thing that sets his cooking apart is a near-religious focus on sauces — he rebuilt them from scratch using extraction and fermentation techniques he developed himself, and calls the result Modern Cuisine. The room is a listed historic monument with early-1900s detailing and windows over the Petit Palais, and the service runs on a "table concierge" idea where the team learns your preferences before you even arrive. Three Michelin stars and a World\'s 50 Best name. Booking is genuinely hard — plan weeks out.'],
    ['atelier-crenn', 'Dominique Crenn', 'Chef Dominique Crenn\'s San Francisco room, where the menu arrives as a poem and dinner follows it line by line.', 'Chef Dominique Crenn opened Atelier Crenn in 2011 as a deeply personal project — "atelier" meaning workshop — and built it around what she calls Poetic Culinaria: your menu is handed over as a poem she wrote, each line corresponding to a course. In 2018 she became the first female chef in the United States to hold three Michelin stars, a genuine line in the sand for the country\'s dining world. The small Marina-district room is hung with her late father\'s paintings, the menu is pescatarian and seafood-forward, and the pastry finale has a reputation all its own. Three Michelin stars. Worth building an evening around.'],
    ['aponiente', 'Ángel León', 'Chef Ángel León\'s "kitchen of the sea," set in an old tide mill on the Cádiz salt marshes.', 'They call Chef Ángel León the Chef of the Sea, and he\'s earned it: working from a centuries-old tide mill on the marshes outside Cádiz, he\'s spent over a decade cooking almost entirely from the ocean, and he\'s the one who introduced edible plankton to fine dining. The meal starts outside, on wooden walkways through recovered estuaries where some of the ingredients are gathered. Inside, the tasting menu runs on things most kitchens discard or never consider — marine "sausages," plankton, lesser-known fish — and even the desserts come from the sea. It was Andalucía\'s first three-Michelin-star restaurant and holds one of the first-ever Michelin Green Stars for sustainability. Worth the detour into the marshes.'],
    ['restaurant-schwarzwaldstube', 'Torsten Michel', 'Deep in the Black Forest, the kitchen that\'s held three Michelin stars longer than any other in Germany.', 'Tucked inside the Traube Tonbach hotel in a pine valley near Baiersbronn, Schwarzwaldstube — "Black Forest parlor" — has held three Michelin stars since 1992, the longest unbroken run of any restaurant in Germany. Chef Torsten Michel took the kitchen over in 2016 from the legendary Harald Wohlfahrt and hasn\'t let the standard slip, working classic French foundations through modern technique with the region\'s own ingredients. The dining room looks straight out over the valley through floor-to-gable glass, and the wine list and pairings are a destination in themselves. A kitchen fire forced a rebuild a few years back; the cooking never missed a beat. Three Michelin stars, and worth the drive into the forest.'],
    ['cocina-hermanos-torres', 'Sergio Torres; Javier Torres', 'In Barcelona, twin brothers built a restaurant that\'s really one enormous kitchen with tables around it.', 'Twin chefs Sergio and Javier Torres opened Cocina Hermanos Torres in 2018 in a converted Barcelona warehouse, and earned three Michelin stars by 2022. The conceit is right there in the room: instead of hiding the kitchen, they put it dead center — cooking islands under soft "clouds" of light, with the tables arranged around them, so dinner plays out as theater. The brothers trace it all back to their grandmother Catalina\'s kitchen, and the Mediterranean cooking leans on seasonal local produce handled with a light touch, like cured squid with poultry consommé and caviar. Three Michelin stars plus a green star for sustainability. Worth building a Barcelona night around.'],
    ['atrio-caceres', 'Toño Pérez; José Polo', 'In medieval Cáceres, a three-star restaurant as famous for its wine cellar as its cooking.', 'Atrio is the decades-long life project of Chef Toño Pérez and his partner, sommelier José Polo — childhood friends who built it inside the UNESCO-listed old town of Cáceres, in Spain\'s quiet Extremadura. The cooking is Pérez\'s love letter to the region: Iberian and Extremaduran ingredients run through modern technique, often built into a long tasting menu around a single product. But the cellar is the stuff of legend — one of the great private wine collections anywhere, vast enough that the list comes as a book, and notorious enough that thieves once pulled off a headline-making heist of its rarest bottles. Three Michelin stars, in a contemporary space folded into medieval stone. Worth the trip out to Extremadura.'],
    ['am-par-alexandre-mazzia', 'Alexandre Mazzia', 'A 20-seat Marseille room where a former pro basketball player serves forty tiny, spice-driven dishes.', 'Chef Alexandre Mazzia took the third Michelin star at AM in 2021, and almost nothing about the place is conventional. He was a professional basketball player before he cooked, he grew up in the Congo, and that childhood runs straight through his food — a virtuoso run of spices, roasting and smoking across some forty small dishes, with signature oddities like smoked-eel chocolate and algae popcorn. The room near the Vélodrome seats only about twenty, kitchen open to the tables, concrete and oak and no tablecloths. The name itself is a double meaning: his initials, and the French word for soul. Three Michelin stars. Come with an open mind and an empty stomach.'],
    ['auberge-du-vieux-puits', 'Gilles Goujon', 'In a tiny Languedoc village, Chef Gilles Goujon\'s three-star country auberge built on trompe-l\'oeil and truffle.', 'You have to mean it to get out to Fontjoncouse — barely a village, deep in the Languedoc backcountry — and that\'s part of the appeal of Chef Gilles Goujon\'s Auberge du Vieux Puits. He holds three Michelin stars out here, cooking that\'s deeply rooted in the local market yet full of playful sleight of hand: textures, precise cooking, trompe-l\'oeil plates that aren\'t what they look like. The dish people travel for is his "rotten" carrus hen egg — truffled, set over mushroom purée, with a warm briochine and a drinkable cappuccino alongside. Three Michelin stars, genuinely off the beaten path. Worth every kilometer of the detour.'],
  ];

  var written = 0, missing = [];
  for (var k = 0; k < OPTION_B.length; k++) {
    var slug = OPTION_B[k][0], chef = OPTION_B[k][1],
        bShort = OPTION_B[k][2], bLong = OPTION_B[k][3];
    var ri = rowOf[slug];
    if (ri === undefined) { missing.push(slug); continue; }
    sheet.getRange(ri + 1, col['blurb_short'] + 1).setValue(bShort);
    sheet.getRange(ri + 1, col['blurb_long'] + 1).setValue(bLong);
    sheet.getRange(ri + 1, col['chef'] + 1).setValue(chef);
    written++;
  }

  var msg =
    'Option B import complete.\n' +
    'rows written: ' + written + ' / ' + OPTION_B.length + '\n' +
    (missing.length
      ? 'NOT FOUND (slug mismatch): ' + missing.join(', ')
      : 'all slugs matched.');
  Logger.log(msg);
  SpreadsheetApp.getUi().alert(msg);
}
