-- source-url-michelin-2026-germany-legacy.sql
-- CompassEats, Oct 8 2026. Open item 1 of handoff-germany-promoted-2026-10-08: Germany option A.
-- Set source_url IN PLACE on the 336 legacy Michelin 2026 rows on German venues that a 2026 card
-- confirms (Ben's decision Q1, Oct 4: option A). Model: docs/source-url-michelin-2026-chengdu-legacy.sql
-- (ledger 84).
-- Source: fixtures/ingest/michelin-2026-germany.csv (483 lines), sha256
--   424ab62fea6b2812f1ac67ac4bff9ca13a256c2ebe8c4e9522b2ded283000bff.
--   The 483 values below are generated by script from that file (no retyping).
--   md5 guard of line|category|source_url (by line, newline): 410643990798c2b5c310529b23944b4b
-- Basis: ingest batch 13 (michelin-2026-germany, promoted Oct 8 23:53:27 UTC), stage run 2.
--   md5 of line|verdict|venue_id|city_id (comma, by line), 483 rows: b12707287e46942f4d5603d98001a4e3
-- Per-row test (read Oct 8): staged verdict `duplicate`, reason duplicate_of_existing_award,
--   exactly 1 collides_with id = the award row, award venue = staged venue, award category =
--   card category, award is Michelin 2026 with no source_url, no rank, no distinction,
--   venue city country_iso DE, staged URL = fixture URL for the same line. 336 of 336 pass.
--   Category: Three Stars 12, Two Stars 47, One Star 277, Bib 0.
--   Price is NOT a test (decision Q1). 3 rows differ (legacy $$$ vs card €€€€: 7906 Rebers Pflug,
--   6670 BOK, 5902 Kuultivo), 30 venues have no price row. Price goes to the price work item.
-- Award id md5 (ids joined with ',' in id order): a107a3ac640e98b768f476f8bfe7852e
-- Plan fingerprint (md5 of award_id|venue_id|category|url, by award_id, newline), read Oct 8:
--   ae4a8405d519950b8bbc3746578e3921 (336 rows).
-- Rows left out: the 2 German legacy 2026 rows with no card, 3578 (Posthotel Alexander Herrmann,
--   Two Stars) and 7349 (Gasthaus Jakob, One Star). They go to the Germany cleanup.
-- Write: 1 UPDATE (336 rows, source_url only) + 1 ledger row. Expected audit rows: 336
--   (trg_audit_awards, UPDATE). The ledger has no audit trigger and no note column, so the
--   note goes in `job` after the job key.
-- Dry run: send only the DO block through the Read connector. All pre-checks run, then the
--   block stops at the UPDATE with "read-only transaction".

BEGIN;
DO $do$
DECLARE
  fxj      jsonb;
  fxmd5    text;
  plan     jsonb;
  n_plan   int;
  fp       text;
  n        int;
  x        int;
  aud_max  bigint;
  aud_n    bigint;
  led_max  bigint;
  led_n    bigint;
  job_txt  text := 'source-url:michelin-2026-germany-legacy | option A (Ben, Oct 4): 336 legacy Michelin 2026 rows on DE venues confirmed by a 2026 card, source_url set in place | live guide.michelin.com/us/en venue pages, one URL per row | fixtures/ingest/michelin-2026-germany.csv sha256 424ab62fea6b2812f1ac67ac4bff9ca13a256c2ebe8c4e9522b2ded283000bff | basis: batch 13 stage verdict duplicate (collides_with = row, venue and category agree) | award ids md5 a107a3ac640e98b768f476f8bfe7852e | left blank, no card: 3578, 7349 (cleanup)';
BEGIN
  -- 0. Source values (generated from the repo file) and their guard
  SELECT jsonb_agg(jsonb_build_object('line', line, 'cat', cat, 'url', url)),
         md5(string_agg(line||'|'||cat||'|'||url, E'\n' ORDER BY line))
    INTO fxj, fxmd5
  FROM (VALUES
(1,'Three Stars','https://guide.michelin.com/us/en/baden-wurttemberg/baiersbronn/restaurant/restaurant-bareiss'),
(2,'Three Stars','https://guide.michelin.com/us/en/baden-wurttemberg/baiersbronn/restaurant/schwarzwaldstube'),
(3,'Three Stars','https://guide.michelin.com/us/en/bayern/grassau/restaurant/es-senz'),
(4,'Three Stars','https://guide.michelin.com/us/en/bayern/mnchen/restaurant/jan-1204321'),
(5,'Three Stars','https://guide.michelin.com/us/en/bayern/mnchen/restaurant/tohru-in-der-schreiberei'),
(6,'Three Stars','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/rutz'),
(7,'Three Stars','https://guide.michelin.com/us/en/hamburg-region/hamburg/restaurant/haerlin'),
(8,'Three Stars','https://guide.michelin.com/us/en/hamburg-region/hamburg/restaurant/the-table-kevin-fehling'),
(9,'Three Stars','https://guide.michelin.com/us/en/rheinland-pfalz/deidesheim/restaurant/l-a-jordan'),
(10,'Three Stars','https://guide.michelin.com/us/en/rheinland-pfalz/dreis/restaurant/waldhotel-sonnora'),
(11,'Three Stars','https://guide.michelin.com/us/en/rheinland-pfalz/piesport/restaurant/schanz-restaurant'),
(12,'Three Stars','https://guide.michelin.com/us/en/saarland/perl/restaurant/victor-s-fine-dining-by-christian-bau'),
(13,'Two Stars','https://guide.michelin.com/us/en/baden-wurttemberg/bad-peterstal/restaurant/le-pavillon83378'),
(14,'Two Stars','https://guide.michelin.com/us/en/baden-wurttemberg/donaueschingen/restaurant/osch-noir'),
(15,'Two Stars','https://guide.michelin.com/us/en/baden-wurttemberg/karlsruhe/restaurant/sein'),
(16,'Two Stars','https://guide.michelin.com/us/en/baden-wurttemberg/konstanz/restaurant/ophelia'),
(17,'Two Stars','https://guide.michelin.com/us/en/baden-wurttemberg/mannheim/restaurant/opus-v'),
(18,'Two Stars','https://guide.michelin.com/us/en/baden-wurttemberg/rust/restaurant/ammolite-the-lighthouse-restaurant'),
(19,'Two Stars','https://guide.michelin.com/us/en/baden-wurttemberg/schluchsee/restaurant/muhle-1195341'),
(20,'Two Stars','https://guide.michelin.com/us/en/baden-wurttemberg/stuttgart/restaurant/speisemeisterei'),
(21,'Two Stars','https://guide.michelin.com/us/en/baden-wurttemberg/sulzburg/restaurant/hirschen78032'),
(22,'Two Stars','https://guide.michelin.com/us/en/baden-wurttemberg/zweiflingen/restaurant/le-cerf83229'),
(23,'Two Stars','https://guide.michelin.com/us/en/bayern/augsburg/restaurant/august495065'),
(24,'Two Stars','https://guide.michelin.com/us/en/bayern/berchtesgaden/restaurant/pur-1187942'),
(25,'Two Stars','https://guide.michelin.com/us/en/bayern/krn/restaurant/ikigai-122205'),
(26,'Two Stars','https://guide.michelin.com/us/en/bayern/mnchen/restaurant/alois-dallmayr-fine-dining'),
(27,'Two Stars','https://guide.michelin.com/us/en/bayern/mnchen/restaurant/atelier-1198719'),
(28,'Two Stars','https://guide.michelin.com/us/en/bayern/mnchen/restaurant/komu'),
(29,'Two Stars','https://guide.michelin.com/us/en/bayern/mnchen/restaurant/tantris-75719'),
(30,'Two Stars','https://guide.michelin.com/us/en/bayern/mnchen/restaurant/the-cloud-by-kafer'),
(31,'Two Stars','https://guide.michelin.com/us/en/bayern/neunburg-vorm-wald/restaurant/obendorfer-s-eisvogel'),
(32,'Two Stars','https://guide.michelin.com/us/en/bayern/nurnberg/restaurant/essigbratlein'),
(33,'Two Stars','https://guide.michelin.com/us/en/bayern/nurnberg/restaurant/etz'),
(34,'Two Stars','https://guide.michelin.com/us/en/bayern/rottach-egern/restaurant/dichterstub-n'),
(35,'Two Stars','https://guide.michelin.com/us/en/bayern/teisnach/restaurant/oswald-s-gourmetstube'),
(36,'Two Stars','https://guide.michelin.com/us/en/bayern/wirsberg/restaurant/alexander-herrmann-by-tobias-batz'),
(37,'Two Stars','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/coda-dessert-dining'),
(38,'Two Stars','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/facil'),
(39,'Two Stars','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/horvath'),
(40,'Two Stars','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/tim-raue'),
(41,'Two Stars','https://guide.michelin.com/us/en/hamburg-region/hamburg/restaurant/100-200'),
(42,'Two Stars','https://guide.michelin.com/us/en/hamburg-region/hamburg/restaurant/lakeside'),
(43,'Two Stars','https://guide.michelin.com/us/en/hessen/frankfurt-am-main/restaurant/lafleur'),
(44,'Two Stars','https://guide.michelin.com/us/en/hessen/frankfurt-am-main/restaurant/rausch'),
(45,'Two Stars','https://guide.michelin.com/us/en/hessen/frankfurt-am-main/restaurant/the-dune'),
(46,'Two Stars','https://guide.michelin.com/us/en/niedersachsen/hannover/restaurant/jante'),
(47,'Two Stars','https://guide.michelin.com/us/en/niedersachsen/hannover/restaurant/votum'),
(48,'Two Stars','https://guide.michelin.com/us/en/nordrhein-westfalen/bergisch-gladbach/restaurant/vendome'),
(49,'Two Stars','https://guide.michelin.com/us/en/nordrhein-westfalen/koln/restaurant/ox-klee'),
(50,'Two Stars','https://guide.michelin.com/us/en/nordrhein-westfalen/munster/restaurant/coeur-d-artichaut'),
(51,'Two Stars','https://guide.michelin.com/us/en/rheinland-pfalz/bad-neuenahr-ahrweiler/restaurant/steinheuers-restaurant-zur-alten-post'),
(52,'Two Stars','https://guide.michelin.com/us/en/rheinland-pfalz/koblenz/restaurant/gotthardt-s-by-yannick-noack'),
(53,'Two Stars','https://guide.michelin.com/us/en/rheinland-pfalz/wachenheim-an-der-weinstrasse/restaurant/intense-1195298'),
(54,'Two Stars','https://guide.michelin.com/us/en/saarland/saarbrucken/restaurant/esplanade539722'),
(55,'Two Stars','https://guide.michelin.com/us/en/saarland/saarbrucken/restaurant/gastehaus-klaus-erfort'),
(56,'Two Stars','https://guide.michelin.com/us/en/saarland/saarlouis/restaurant/louis-restaurant'),
(57,'Two Stars','https://guide.michelin.com/us/en/saarland/sankt-ingbert/restaurant/atama-by-martin-stopp'),
(58,'Two Stars','https://guide.michelin.com/us/en/sachsen-anhalt/wernigerode/restaurant/pietsch'),
(59,'Two Stars','https://guide.michelin.com/us/en/schleswig-holstein/glcksburg/restaurant/meierei-dirk-luther'),
(60,'Two Stars','https://guide.michelin.com/us/en/schleswig-holstein/rantum/restaurant/sol-ring-hof'),
(61,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/asperg/restaurant/schwabenstube'),
(62,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/bad-krozingen/restaurant/storchen'),
(63,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/bad-sckingen/restaurant/genuss-apotheke'),
(64,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/bad-teinach-zavelstein/restaurant/gourmetrestaurant-berlins-krone'),
(65,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/baden-baden/restaurant/le-jardin-de-france'),
(66,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/baden-baden/restaurant/maltes-hidden-kitchen'),
(67,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/baiersbronn/restaurant/1789-1191834'),
(68,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/baiersbronn/restaurant/schlossberg'),
(69,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/bietigheim-bissingen/restaurant/maerz-das-restaurant'),
(70,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/de-schwbisch-hall/restaurant/eisenbahn'),
(71,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/de-schwbisch-hall/restaurant/rebers-pflug'),
(72,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/donaueschingen/restaurant/die-burg'),
(73,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/efringen-kirchen/restaurant/traube1181496'),
(74,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/eggenstein-leopoldshafen/restaurant/das-garbo-im-lowen'),
(75,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/ehningen/restaurant/landhaus-feckl'),
(76,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/endingen-am-kaiserstuhl/restaurant/merkles-restaurant'),
(77,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/ettlingen/restaurant/erbprinz'),
(78,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/fellbach/restaurant/oettinger-s-restaurant'),
(79,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/freiburg-im-breisgau/restaurant/colombi-restaurant'),
(80,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/freiburg-im-breisgau/restaurant/eichhalde'),
(81,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/freiburg-im-breisgau/restaurant/hawara'),
(82,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/freiburg-im-breisgau/restaurant/jacobi'),
(83,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/freiburg-im-breisgau/restaurant/wolfshohle-1198858'),
(84,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/gernsbach/restaurant/werners-restaurant99887'),
(85,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/grenzach-wyhlen/restaurant/eckert'),
(86,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/hayingen/restaurant/restaurant-1950'),
(87,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/heidelberg/restaurant/oben'),
(88,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/kernen-im-remstal/restaurant/malathounis'),
(89,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/knigsbronn/restaurant/ursprung'),
(90,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/lahr/restaurant/adler82171'),
(91,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/langenau/restaurant/hochzwei'),
(92,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/mannheim/restaurant/doblers'),
(93,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/mannheim/restaurant/the-tourist-trap'),
(94,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/neuhausen/restaurant/alte-baiz'),
(95,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/ohningen/restaurant/falconera'),
(96,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/ravensburg/restaurant/kaisersaal'),
(97,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/rust/restaurant/eatrenalin'),
(98,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/rutesheim_1316036/restaurant/das-philippin'),
(99,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/salach/restaurant/gourmetrestaurant-fine-dining-rs'),
(100,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/schorndorf/restaurant/gourmetrestaurant-nico-burkhardt'),
(101,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/schriesheim/restaurant/raro-im-muhlenhof'),
(102,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/schwendi/restaurant/esszimmer-im-oberschwabischen-hof-1195566'),
(103,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/sonnenbhl/restaurant/hirsch77747'),
(104,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/stuttgart/restaurant/5'),
(105,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/stuttgart/restaurant/delice'),
(106,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/stuttgart/restaurant/der-zauberlehrling'),
(107,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/stuttgart/restaurant/hupperts'),
(108,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/stuttgart/restaurant/laesa'),
(109,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/stuttgart/restaurant/wielandshohe'),
(110,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/stuttgart/restaurant/zur-weinsteige'),
(111,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/tuttlingen/restaurant/anima'),
(112,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/uhingen/restaurant/schloss-filseck'),
(113,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/ulm/restaurant/bi-braud'),
(114,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/ulm/restaurant/seestern'),
(115,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/vaihingen-an-der-enz/restaurant/lamm-rosswag'),
(116,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/vogtsburg-im-kaiserstuhl/restaurant/schwarzer-adler'),
(117,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/waiblingen/restaurant/bachofer'),
(118,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/waldbronn/restaurant/schwitzer-s-am-park'),
(119,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/waldenbuch/restaurant/gasthof-krone'),
(120,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/weil-am-rhein/restaurant/cafe-gupi'),
(121,'One Star','https://guide.michelin.com/us/en/baden-wurttemberg/weinstadt/restaurant/cedric-1204630'),
(122,'One Star','https://guide.michelin.com/us/en/bayern/aschau-im-chiemgau/restaurant/restaurant-heinz-winkler'),
(123,'One Star','https://guide.michelin.com/us/en/bayern/auerbach-in-der-oberpfalz/restaurant/soulfood'),
(124,'One Star','https://guide.michelin.com/us/en/bayern/augsburg/restaurant/alte-liebe'),
(125,'One Star','https://guide.michelin.com/us/en/bayern/augsburg/restaurant/nose-belly'),
(126,'One Star','https://guide.michelin.com/us/en/bayern/augsburg/restaurant/sartory'),
(127,'One Star','https://guide.michelin.com/us/en/bayern/bad-kissingen/restaurant/laudensacks-gourmet-restaurant'),
(128,'One Star','https://guide.michelin.com/us/en/bayern/bad-ktzing/restaurant/leos-by-stephan-brandl'),
(129,'One Star','https://guide.michelin.com/us/en/bayern/bernried_1281441/restaurant/schwingshackl-esskultur'),
(130,'One Star','https://guide.michelin.com/us/en/bayern/bischofswiesen/restaurant/solo-du'),
(131,'One Star','https://guide.michelin.com/us/en/bayern/deggendorf_1282003/restaurant/edl-eins-fine-dining'),
(132,'One Star','https://guide.michelin.com/us/en/bayern/duggendorf/restaurant/hummels-gourmetstube'),
(133,'One Star','https://guide.michelin.com/us/en/bayern/eichsttt/restaurant/staderer'),
(134,'One Star','https://guide.michelin.com/us/en/bayern/frasdorf/restaurant/michael-s-leitenberg'),
(135,'One Star','https://guide.michelin.com/us/en/bayern/frasdorf/restaurant/restaurant-karner'),
(136,'One Star','https://guide.michelin.com/us/en/bayern/illschwang/restaurant/cheval-blanc554556'),
(137,'One Star','https://guide.michelin.com/us/en/bayern/kirchdorf/restaurant/christian-s-restaurant-gasthof-grainer'),
(138,'One Star','https://guide.michelin.com/us/en/bayern/klingenberg-am-main/restaurant/colbo'),
(139,'One Star','https://guide.michelin.com/us/en/bayern/kreuzwertheim_1295241/restaurant/la-boucherie'),
(140,'One Star','https://guide.michelin.com/us/en/bayern/landsberg-am-lech_1299909/restaurant/lech-line'),
(141,'One Star','https://guide.michelin.com/us/en/bayern/langenzenn/restaurant/keidenzeller-hof'),
(142,'One Star','https://guide.michelin.com/us/en/bayern/lindau/restaurant/karrisma'),
(143,'One Star','https://guide.michelin.com/us/en/bayern/lindau/restaurant/villino'),
(144,'One Star','https://guide.michelin.com/us/en/bayern/markt-indersdorf_1300191/restaurant/mind-1209794'),
(145,'One Star','https://guide.michelin.com/us/en/bayern/mittenwald/restaurant/das-marktrestaurant'),
(146,'One Star','https://guide.michelin.com/us/en/bayern/mnchen/restaurant/1804-hirschau'),
(147,'One Star','https://guide.michelin.com/us/en/bayern/mnchen/restaurant/brothers'),
(148,'One Star','https://guide.michelin.com/us/en/bayern/mnchen/restaurant/gabelspiel'),
(149,'One Star','https://guide.michelin.com/us/en/bayern/mnchen/restaurant/les-deux'),
(150,'One Star','https://guide.michelin.com/us/en/bayern/mnchen/restaurant/mountain-hub-gourmet'),
(151,'One Star','https://guide.michelin.com/us/en/bayern/mnchen/restaurant/sparkling-bistro'),
(152,'One Star','https://guide.michelin.com/us/en/bayern/mnchen/restaurant/tantris-dna'),
(153,'One Star','https://guide.michelin.com/us/en/bayern/mnchen/restaurant/werneckhof-sigi-schelling'),
(154,'One Star','https://guide.michelin.com/us/en/bayern/neu-ulm/restaurant/stephans-stuben'),
(155,'One Star','https://guide.michelin.com/us/en/bayern/niederwinkling/restaurant/buchner'),
(156,'One Star','https://guide.michelin.com/us/en/bayern/nrdlingen/restaurant/wirtshaus-meyers-keller'),
(157,'One Star','https://guide.michelin.com/us/en/bayern/nurnberg/restaurant/entenstuben'),
(158,'One Star','https://guide.michelin.com/us/en/bayern/nurnberg/restaurant/tisane'),
(159,'One Star','https://guide.michelin.com/us/en/bayern/nurnberg/restaurant/veles'),
(160,'One Star','https://guide.michelin.com/us/en/bayern/nurnberg/restaurant/waidwerk'),
(161,'One Star','https://guide.michelin.com/us/en/bayern/nurnberg/restaurant/wonka'),
(162,'One Star','https://guide.michelin.com/us/en/bayern/nurnberg/restaurant/zweisinn-meiers-fine-dining'),
(163,'One Star','https://guide.michelin.com/us/en/bayern/oberstdorf/restaurant/ess-atelier-strauss'),
(164,'One Star','https://guide.michelin.com/us/en/bayern/ofterschwang/restaurant/silberdistel'),
(165,'One Star','https://guide.michelin.com/us/en/bayern/passau/restaurant/marcel-von-winckelmann'),
(166,'One Star','https://guide.michelin.com/us/en/bayern/pfronten/restaurant/pavo-im-burghotel-falkenstein'),
(167,'One Star','https://guide.michelin.com/us/en/bayern/pleiskirchen/restaurant/huberwirt'),
(168,'One Star','https://guide.michelin.com/us/en/bayern/prien-am-chiemsee/restaurant/wachter-foodbar'),
(169,'One Star','https://guide.michelin.com/us/en/bayern/regensburg/restaurant/aska-1186893'),
(170,'One Star','https://guide.michelin.com/us/en/bayern/regensburg/restaurant/ontra-s-gourmetstube'),
(171,'One Star','https://guide.michelin.com/us/en/bayern/regensburg/restaurant/storstad'),
(172,'One Star','https://guide.michelin.com/us/en/bayern/rothenburg-ob-der-tauber/restaurant/mittermeier'),
(173,'One Star','https://guide.michelin.com/us/en/bayern/rottach-egern/restaurant/haubentaucher'),
(174,'One Star','https://guide.michelin.com/us/en/bayern/rottach-egern/restaurant/restaurant-uberfahrt'),
(175,'One Star','https://guide.michelin.com/us/en/bayern/simmershofen_1306812/restaurant/winzerhof-stahl'),
(176,'One Star','https://guide.michelin.com/us/en/bayern/sommerhausen/restaurant/philipp'),
(177,'One Star','https://guide.michelin.com/us/en/bayern/starnberg/restaurant/aubergine388304'),
(178,'One Star','https://guide.michelin.com/us/en/bayern/ubersee_1280400/restaurant/june-1213481'),
(179,'One Star','https://guide.michelin.com/us/en/bayern/volkach/restaurant/weinstock'),
(180,'One Star','https://guide.michelin.com/us/en/bayern/waldkirchen/restaurant/johanns'),
(181,'One Star','https://guide.michelin.com/us/en/bayern/weissenbrunn/restaurant/gasthof-alex'),
(182,'One Star','https://guide.michelin.com/us/en/bayern/wurzburg/restaurant/kuno-1408'),
(183,'One Star','https://guide.michelin.com/us/en/bayern/wurzburg/restaurant/mizar'),
(184,'One Star','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/bandol-sur-mer'),
(185,'One Star','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/bonvivant-1197308'),
(186,'One Star','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/bricole'),
(187,'One Star','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/cookies-cream'),
(188,'One Star','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/golvet'),
(189,'One Star','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/hallmann-und-klee'),
(190,'One Star','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/hugos'),
(191,'One Star','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/irma-la-douce'),
(192,'One Star','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/lorenz-adlon-esszimmer'),
(193,'One Star','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/loumi'),
(194,'One Star','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/matthias'),
(195,'One Star','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/nobelhart-schmutzig'),
(196,'One Star','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/pars-restaurant'),
(197,'One Star','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/tulus-lotrek'),
(198,'One Star','https://guide.michelin.com/us/en/brandenburg/falkensee_1318711/restaurant/sawito'),
(199,'One Star','https://guide.michelin.com/us/en/brandenburg/werder/restaurant/alte-uberfahrt'),
(200,'One Star','https://guide.michelin.com/us/en/hamburg-region/hamburg/restaurant/arc-restaurant'),
(201,'One Star','https://guide.michelin.com/us/en/hamburg-region/hamburg/restaurant/atlantic-restaurant'),
(202,'One Star','https://guide.michelin.com/us/en/hamburg-region/hamburg/restaurant/glorie'),
(203,'One Star','https://guide.michelin.com/us/en/hamburg-region/hamburg/restaurant/haebel'),
(204,'One Star','https://guide.michelin.com/us/en/hamburg-region/hamburg/restaurant/heimatjuwel'),
(205,'One Star','https://guide.michelin.com/us/en/hamburg-region/hamburg/restaurant/jellyfish'),
(206,'One Star','https://guide.michelin.com/us/en/hamburg-region/hamburg/restaurant/koer'),
(207,'One Star','https://guide.michelin.com/us/en/hamburg-region/hamburg/restaurant/landhaus-scherrer'),
(208,'One Star','https://guide.michelin.com/us/en/hamburg-region/hamburg/restaurant/petit-amour'),
(209,'One Star','https://guide.michelin.com/us/en/hamburg-region/hamburg/restaurant/piment'),
(210,'One Star','https://guide.michelin.com/us/en/hamburg-region/hamburg/restaurant/the-lisbeth'),
(211,'One Star','https://guide.michelin.com/us/en/hamburg-region/hamburg/restaurant/zeik'),
(212,'One Star','https://guide.michelin.com/us/en/hessen/bad-hersfeld/restaurant/l-etable164933'),
(213,'One Star','https://guide.michelin.com/us/en/hessen/darmstadt/restaurant/ox-1194853'),
(214,'One Star','https://guide.michelin.com/us/en/hessen/eltville-am-rhein/restaurant/ente'),
(215,'One Star','https://guide.michelin.com/us/en/hessen/eltville-am-rhein/restaurant/jean'),
(216,'One Star','https://guide.michelin.com/us/en/hessen/frankenberg/restaurant/philipp-soldan'),
(217,'One Star','https://guide.michelin.com/us/en/hessen/frankfurt-am-main/restaurant/bidlabu'),
(218,'One Star','https://guide.michelin.com/us/en/hessen/frankfurt-am-main/restaurant/erno-s-bistro'),
(219,'One Star','https://guide.michelin.com/us/en/hessen/frankfurt-am-main/restaurant/lohninger'),
(220,'One Star','https://guide.michelin.com/us/en/hessen/frankfurt-am-main/restaurant/main-tower-restaurant-lounge-1198316'),
(221,'One Star','https://guide.michelin.com/us/en/hessen/frankfurt-am-main/restaurant/masa-japanese-cuisine'),
(222,'One Star','https://guide.michelin.com/us/en/hessen/frankfurt-am-main/restaurant/restaurant-villa-merton'),
(223,'One Star','https://guide.michelin.com/us/en/hessen/frankfurt-am-main/restaurant/seven-swans'),
(224,'One Star','https://guide.michelin.com/us/en/hessen/frankfurt-am-main/restaurant/sommerfeld'),
(225,'One Star','https://guide.michelin.com/us/en/hessen/fulda/restaurant/christian-friends-tastekitchen'),
(226,'One Star','https://guide.michelin.com/us/en/hessen/herleshausen/restaurant/la-vallee-verte'),
(227,'One Star','https://guide.michelin.com/us/en/hessen/limburg-an-der-lahn/restaurant/360%C2%B0'),
(228,'One Star','https://guide.michelin.com/us/en/mecklenburg-vorpommern/bad-doberan/restaurant/friedrich-franz'),
(229,'One Star','https://guide.michelin.com/us/en/mecklenburg-vorpommern/dierhagen/restaurant/ostseelounge-1214302'),
(230,'One Star','https://guide.michelin.com/us/en/mecklenburg-vorpommern/feldberger-seenlandschaft/restaurant/alte-schule-klassenzimmer'),
(231,'One Star','https://guide.michelin.com/us/en/mecklenburg-vorpommern/heringsdorf/restaurant/kulmeck-by-tom-wickboldt'),
(232,'One Star','https://guide.michelin.com/us/en/mecklenburg-vorpommern/krakow-am-see/restaurant/ich-weiss-ein-haus-am-see'),
(233,'One Star','https://guide.michelin.com/us/en/mecklenburg-vorpommern/ostseebad-binz/restaurant/freustil'),
(234,'One Star','https://guide.michelin.com/us/en/mecklenburg-vorpommern/rostock/restaurant/gourmet-restaurant-der-butt'),
(235,'One Star','https://guide.michelin.com/us/en/mecklenburg-vorpommern/schwerin/restaurant/gourmetrestaurant-1751'),
(236,'One Star','https://guide.michelin.com/us/en/niedersachsen/bad-sachsa_1334125/restaurant/joseph-s-fine-dining'),
(237,'One Star','https://guide.michelin.com/us/en/niedersachsen/cuxhaven/restaurant/sterneck'),
(238,'One Star','https://guide.michelin.com/us/en/niedersachsen/hannover/restaurant/handwerk'),
(239,'One Star','https://guide.michelin.com/us/en/niedersachsen/hannover/restaurant/marie-1204342'),
(240,'One Star','https://guide.michelin.com/us/en/niedersachsen/hohnhorst_1337121/restaurant/restaurant-mohn'),
(241,'One Star','https://guide.michelin.com/us/en/niedersachsen/norderney/restaurant/seesteg'),
(242,'One Star','https://guide.michelin.com/us/en/niedersachsen/osnabruck/restaurant/iko'),
(243,'One Star','https://guide.michelin.com/us/en/niedersachsen/osnabruck/restaurant/kesselhaus1179716'),
(244,'One Star','https://guide.michelin.com/us/en/niedersachsen/seesen_1340885/restaurant/harzfenster-by-johannes-steingruber'),
(245,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/aachen/restaurant/la-becasse'),
(246,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/aachen/restaurant/sankt-benedikt'),
(247,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/bergisch-gladbach/restaurant/schote-1215854'),
(248,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/bonn/restaurant/halbedel-s-gasthaus'),
(249,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/bonn/restaurant/theodor-s'),
(250,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/bonn/restaurant/yunico'),
(251,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/detmold/restaurant/porte-neuf'),
(252,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/dorsten/restaurant/goldener-anker'),
(253,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/dorsten/restaurant/rosin'),
(254,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/dortmund/restaurant/schwarzgold'),
(255,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/duisburg/restaurant/mod-by-sven-nothel'),
(256,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/dusseldorf/restaurant/agata-s'),
(257,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/dusseldorf/restaurant/im-schiffchen'),
(258,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/dusseldorf/restaurant/jae-1205584'),
(259,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/dusseldorf/restaurant/la-vie-by-thomas-buhner-1210743'),
(260,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/dusseldorf/restaurant/nagaya'),
(261,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/dusseldorf/restaurant/setzkasten'),
(262,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/dusseldorf/restaurant/tafelspitz-1876'),
(263,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/dusseldorf/restaurant/yoshi-by-nagaya'),
(264,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/dusseldorf/restaurant/zwanzig23-by-lukas-jakobi'),
(265,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/erkelenz/restaurant/troyka'),
(266,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/essen/restaurant/chefs-atelier'),
(267,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/essen/restaurant/hannappel'),
(268,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/essen/restaurant/kettner-s-kamota'),
(269,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/essen/restaurant/teko-by-lange-rodriguez'),
(270,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/gummersbach/restaurant/muhlenhelle'),
(271,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/haltern-am-see/restaurant/ratsstuben'),
(272,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/koln/restaurant/la-cuisine-rademacher'),
(273,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/koln/restaurant/la-societe'),
(274,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/koln/restaurant/le-moissonnier'),
(275,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/koln/restaurant/maximilian-lorenz'),
(276,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/koln/restaurant/neobiota'),
(277,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/koln/restaurant/pottkind'),
(278,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/koln/restaurant/sahila-the-restaurant'),
(279,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/koln/restaurant/taku'),
(280,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/koln/restaurant/zur-tant'),
(281,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/meerbusch/restaurant/anthony-s-kitchen'),
(282,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/munster/restaurant/brust-oder-keule'),
(283,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/munster/restaurant/spitzner'),
(284,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/odenthal/restaurant/zur-post83223'),
(285,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/paderborn/restaurant/balthasar'),
(286,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/pulheim/restaurant/gut-larchenhof'),
(287,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/rheda-wiedenbrck/restaurant/reuter'),
(288,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/schmallenberg/restaurant/hofstube'),
(289,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/sprockhvel/restaurant/tante-anna'),
(290,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/velbert/restaurant/haus-stemberg'),
(291,'One Star','https://guide.michelin.com/us/en/nordrhein-westfalen/wuppertal/restaurant/shiraz'),
(292,'One Star','https://guide.michelin.com/us/en/rheinland-pfalz/andernach/restaurant/purs'),
(293,'One Star','https://guide.michelin.com/us/en/rheinland-pfalz/bad-neuenahr-ahrweiler/restaurant/historisches-gasthaus-sanct-peter-restaurant-brogsitter'),
(294,'One Star','https://guide.michelin.com/us/en/rheinland-pfalz/birkweiler/restaurant/schockes-kuche'),
(295,'One Star','https://guide.michelin.com/us/en/rheinland-pfalz/darscheid/restaurant/kucher-s-gourmet'),
(296,'One Star','https://guide.michelin.com/us/en/rheinland-pfalz/deidesheim/restaurant/schwarzer-hahn'),
(297,'One Star','https://guide.michelin.com/us/en/rheinland-pfalz/kirchheim-an-der-weinstrasse/restaurant/schwarz-gourmet'),
(298,'One Star','https://guide.michelin.com/us/en/rheinland-pfalz/knittelsheim/restaurant/irori-1214842'),
(299,'One Star','https://guide.michelin.com/us/en/rheinland-pfalz/koblenz/restaurant/schiller-s-restaurant'),
(300,'One Star','https://guide.michelin.com/us/en/rheinland-pfalz/koblenz/restaurant/verbene'),
(301,'One Star','https://guide.michelin.com/us/en/rheinland-pfalz/mainz/restaurant/favorite-restaurant'),
(302,'One Star','https://guide.michelin.com/us/en/rheinland-pfalz/mainz/restaurant/stein-s-traube'),
(303,'One Star','https://guide.michelin.com/us/en/rheinland-pfalz/massweiler/restaurant/borst'),
(304,'One Star','https://guide.michelin.com/us/en/rheinland-pfalz/meisenheim/restaurant/meisenheimer-hof'),
(305,'One Star','https://guide.michelin.com/us/en/rheinland-pfalz/naurath-wald/restaurant/russel-s-landhaus'),
(306,'One Star','https://guide.michelin.com/us/en/rheinland-pfalz/neuhtten/restaurant/le-temple'),
(307,'One Star','https://guide.michelin.com/us/en/rheinland-pfalz/pirmasens/restaurant/die-brasserie'),
(308,'One Star','https://guide.michelin.com/us/en/rheinland-pfalz/saarburg_1332732/restaurant/dopamin'),
(309,'One Star','https://guide.michelin.com/us/en/rheinland-pfalz/selzen/restaurant/kaupers-restaurant-im-kapellenhof'),
(310,'One Star','https://guide.michelin.com/us/en/rheinland-pfalz/trier/restaurant/bagatelle-78242'),
(311,'One Star','https://guide.michelin.com/us/en/rheinland-pfalz/trittenheim/restaurant/wein-und-tafelhaus'),
(312,'One Star','https://guide.michelin.com/us/en/rheinland-pfalz/weisenheim-am-berg/restaurant/admiral'),
(313,'One Star','https://guide.michelin.com/us/en/saarland/blieskastel/restaurant/hammerle-s-restaurant-barrique'),
(314,'One Star','https://guide.michelin.com/us/en/saarland/sankt-ingbert/restaurant/midi'),
(315,'One Star','https://guide.michelin.com/us/en/saarland/sankt-wendel/restaurant/kunz'),
(316,'One Star','https://guide.michelin.com/us/en/sachsen-anhalt/halle-saale/restaurant/speiseberg'),
(317,'One Star','https://guide.michelin.com/us/en/sachsen-anhalt/wernigerode/restaurant/zeitwerk'),
(318,'One Star','https://guide.michelin.com/us/en/sachsen/aue/restaurant/st-andreas'),
(319,'One Star','https://guide.michelin.com/us/en/sachsen/dresden/restaurant/elements351459'),
(320,'One Star','https://guide.michelin.com/us/en/sachsen/dresden/restaurant/genuss-atelier'),
(321,'One Star','https://guide.michelin.com/us/en/sachsen/dresden/restaurant/heiderand'),
(322,'One Star','https://guide.michelin.com/us/en/sachsen/leipzig/restaurant/frieda'),
(323,'One Star','https://guide.michelin.com/us/en/sachsen/leipzig/restaurant/kuultivo'),
(324,'One Star','https://guide.michelin.com/us/en/sachsen/leipzig/restaurant/stadtpfeiffer'),
(325,'One Star','https://guide.michelin.com/us/en/sachsen/radebeul/restaurant/atelier-sanssouci'),
(326,'One Star','https://guide.michelin.com/us/en/schleswig-holstein/flensburg/restaurant/das-grace'),
(327,'One Star','https://guide.michelin.com/us/en/schleswig-holstein/hrnum/restaurant/kai3'),
(328,'One Star','https://guide.michelin.com/us/en/schleswig-holstein/keitum/restaurant/tipken%C2%B4s'),
(329,'One Star','https://guide.michelin.com/us/en/schleswig-holstein/kiel/restaurant/ahlmanns'),
(330,'One Star','https://guide.michelin.com/us/en/schleswig-holstein/lubeck/restaurant/wullenwever'),
(331,'One Star','https://guide.michelin.com/us/en/schleswig-holstein/scharbeutz/restaurant/diva'),
(332,'One Star','https://guide.michelin.com/us/en/schleswig-holstein/timmendorfer-strand/restaurant/orangerie78167'),
(333,'One Star','https://guide.michelin.com/us/en/schleswig-holstein/tinnum/restaurant/bodendorf-s'),
(334,'One Star','https://guide.michelin.com/us/en/schleswig-holstein/wyk/restaurant/alt-wyk'),
(335,'One Star','https://guide.michelin.com/us/en/thuringen/blankenhain/restaurant/masters'),
(336,'One Star','https://guide.michelin.com/us/en/thuringen/blankenhain/restaurant/the-first'),
(337,'One Star','https://guide.michelin.com/us/en/thuringen/dermbach/restaurant/bjornsox'),
(338,'One Star','https://guide.michelin.com/us/en/thuringen/erfurt/restaurant/clara-restaurant-im-kaisersaal'),
(339,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/bad-herrenalb/restaurant/lamm81508'),
(340,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/bad-peterstal/restaurant/kamin-und-bauernstube'),
(341,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/bad-rippoldsau/restaurant/klosterle-hof'),
(342,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/baden-baden/restaurant/weinstube-zum-engel'),
(343,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/baiersbronn/restaurant/dorfstuben'),
(344,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/baiersbronn/restaurant/schatzhauser'),
(345,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/berghaupten/restaurant/hirsch80990'),
(346,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/bonndorf-im-schwarzwald/restaurant/sommerau'),
(347,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/de-schwbisch-hall/restaurant/landhaus-zum-rossle'),
(348,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/ellwangen-(jagst)_1313960/restaurant/hirsch-1207191'),
(349,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/elzach/restaurant/rossle'),
(350,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/elzach/restaurant/schack-s-adler'),
(351,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/endingen-am-kaiserstuhl/restaurant/die-pfarrwirtschaft'),
(352,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/endingen-am-kaiserstuhl/restaurant/dutters-stube'),
(353,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/freiamt/restaurant/zur-krone72877'),
(354,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/frickingen/restaurant/lowen72973'),
(355,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/friedrichshafen_1309211/restaurant/pinus-im-seegut'),
(356,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/grenzach-wyhlen/restaurant/ruhrberger-hof'),
(357,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/hayingen/restaurant/rose'),
(358,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/immenstaad-am-bodensee/restaurant/seehof'),
(359,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/isny-im-allgu/restaurant/allgauer-stuben'),
(360,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/kappelrodeck/restaurant/zum-rebstock'),
(361,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/karlsruhe/restaurant/bistro-margarete'),
(362,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/kenzingen/restaurant/scheidels-restaurant-zum-kranz'),
(363,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/kleines-wiesental/restaurant/sennhutte'),
(364,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/langenau/restaurant/stube-zwei-null'),
(365,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/mittelbiberach_1310820/restaurant/esszimmer-1204759'),
(366,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/oberboihingen/restaurant/zur-linde76225'),
(367,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/ostrach/restaurant/landhotel-zum-hirsch'),
(368,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/sankt-mrgen/restaurant/zum-kreuz'),
(369,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/schluchsee/restaurant/brasserie-barbara'),
(370,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/staufen-im-breisgau/restaurant/die-krone'),
(371,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/sthlingen/restaurant/gasthaus-schwanen77903'),
(372,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/sulzbach_1316547/restaurant/krone-1209640'),
(373,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/sulzburg/restaurant/landgasthof-rebstock'),
(374,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/tengen/restaurant/gasthof-zur-sonne78132'),
(375,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/tiefenbronn/restaurant/bauernstuben'),
(376,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/todtnau/restaurant/derwaldfrieden'),
(377,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/weinheim/restaurant/ziegler'),
(378,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/wildberg/restaurant/talblick'),
(379,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/winterbach/restaurant/landgasthaus-hirsch'),
(380,'Bib Gourmand','https://guide.michelin.com/us/en/baden-wurttemberg/zell-im-wiesental/restaurant/berggasthof-schlussel'),
(381,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/adelshofen/restaurant/zum-falken'),
(382,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/aldersbach/restaurant/das-asam'),
(383,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/bad-tlz/restaurant/jagerwirt'),
(384,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/bergkirchen/restaurant/gasthaus-weissenbeck'),
(385,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/bernried_1281441/restaurant/schwingshackl-heimatkuche-1213862'),
(386,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/bischofswiesen/restaurant/kulturhof-stanggass-gasthaus'),
(387,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/brugstadt/restaurant/weinhaus-stern'),
(388,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/cham/restaurant/gasthaus-odenturm'),
(389,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/dietramszell/restaurant/moarwirt'),
(390,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/dinkelsbhl/restaurant/ehemalige-sparkasse'),
(391,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/erlangen/restaurant/holzgarten'),
(392,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/finning/restaurant/zum-staudenwirt'),
(393,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/forstinning/restaurant/zum-vaas'),
(394,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/frammersbach/restaurant/schwarzkopf'),
(395,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/friedberg/restaurant/gasthaus-goldener-stern'),
(396,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/frstenfeldbruck/restaurant/furstenfelder'),
(397,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/gmund-am-tegernsee/restaurant/ostiner-stub-n'),
(398,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/grossheubach/restaurant/zur-krone'),
(399,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/hauzenberg/restaurant/anetseder'),
(400,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/hauzenberg/restaurant/landgasthaus-gidibauer-hof'),
(401,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/illertissen/restaurant/vier-jahreszeiten-restaurant-imhof'),
(402,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/kirchlauter/restaurant/gutshof-andres'),
(403,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/kreuzwertheim_1295241/restaurant/landgasthof-zum-kaffelstein'),
(404,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/marktbergel/restaurant/rotes-ross164952'),
(405,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/marktbreit/restaurant/alter-esel'),
(406,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/marktbreit/restaurant/michels-stern'),
(407,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/mnchen/restaurant/gasthaus-waltz'),
(408,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/mnchen/restaurant/mokum'),
(409,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/neubeuern/restaurant/auers-schlosswirtschaft'),
(410,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/oberstdorf/restaurant/das-fetzwerk'),
(411,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/oberstdorf/restaurant/das-jagdhaus'),
(412,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/piding/restaurant/lohmayr-stub-n'),
(413,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/pilsach/restaurant/landgasthof-meier'),
(414,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/presseck/restaurant/gasthof-berghof-ursprung'),
(415,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/prien-am-chiemsee/restaurant/zum-fischer-am-see'),
(416,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/rdental/restaurant/froschgrundsee'),
(417,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/regensburg/restaurant/sticky-fingers'),
(418,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/riedenburg/restaurant/forst-s-landhaus'),
(419,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/ruderting/restaurant/landgasthof-zum-muller'),
(420,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/samerberg/restaurant/gasthof-alpenrose'),
(421,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/spalt/restaurant/gasthof-blumenthal'),
(422,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/spiegelau_1291351/restaurant/das-palmberger-hoamart'),
(423,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/vhringen/restaurant/speisemeisterei-burgthalschenke'),
(424,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/wackersberg/restaurant/tolzer-schiessstatte-hager'),
(425,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/waging-am-see/restaurant/landhaus-tanner'),
(426,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/weissenstadt/restaurant/gasthaus-egertal'),
(427,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/wernberg-kblitz/restaurant/wirtsstube'),
(428,'Bib Gourmand','https://guide.michelin.com/us/en/bayern/windorf/restaurant/feilmeiers-landleben'),
(429,'Bib Gourmand','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/barra'),
(430,'Bib Gourmand','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/byblos-1245987'),
(431,'Bib Gourmand','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/lucky-leek'),
(432,'Bib Gourmand','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/mami-s'),
(433,'Bib Gourmand','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/mastan'),
(434,'Bib Gourmand','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/november-brasserie'),
(435,'Bib Gourmand','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/nussbaumerin'),
(436,'Bib Gourmand','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/remi'),
(437,'Bib Gourmand','https://guide.michelin.com/us/en/berlin-region/berlin/restaurant/salhino'),
(438,'Bib Gourmand','https://guide.michelin.com/us/en/brandenburg/neuzelle_1322193/restaurant/wilde-klosterkuche'),
(439,'Bib Gourmand','https://guide.michelin.com/us/en/hamburg-region/hamburg/restaurant/cyn-cyn'),
(440,'Bib Gourmand','https://guide.michelin.com/us/en/hamburg-region/hamburg/restaurant/gassenhaur'),
(441,'Bib Gourmand','https://guide.michelin.com/us/en/hamburg-region/hamburg/restaurant/hygge-brasserie-bar'),
(442,'Bib Gourmand','https://guide.michelin.com/us/en/hamburg-region/hamburg/restaurant/lenz'),
(443,'Bib Gourmand','https://guide.michelin.com/us/en/hamburg-region/hamburg/restaurant/nil'),
(444,'Bib Gourmand','https://guide.michelin.com/us/en/hamburg-region/hamburg/restaurant/zur-flottbeker-schmiede'),
(445,'Bib Gourmand','https://guide.michelin.com/us/en/hessen/frankfurt-am-main/restaurant/bornheimer-ratskeller'),
(446,'Bib Gourmand','https://guide.michelin.com/us/en/hessen/frankfurt-am-main/restaurant/yaldy'),
(447,'Bib Gourmand','https://guide.michelin.com/us/en/hessen/freiensteinau/restaurant/landgasthof-zur-post'),
(448,'Bib Gourmand','https://guide.michelin.com/us/en/hessen/hchst-im-odenwald/restaurant/gaststube81589'),
(449,'Bib Gourmand','https://guide.michelin.com/us/en/mecklenburg-vorpommern/schwerin/restaurant/cube-by-mika'),
(450,'Bib Gourmand','https://guide.michelin.com/us/en/niedersachsen/bad-nenndorf/restaurant/august82886'),
(451,'Bib Gourmand','https://guide.michelin.com/us/en/niedersachsen/dornum/restaurant/fahrhaus'),
(452,'Bib Gourmand','https://guide.michelin.com/us/en/niedersachsen/friesoythe_1344188/restaurant/regional-friesoythe'),
(453,'Bib Gourmand','https://guide.michelin.com/us/en/niedersachsen/lneburg/restaurant/rohms-deli'),
(454,'Bib Gourmand','https://guide.michelin.com/us/en/nordrhein-westfalen/aachen/restaurant/bistro356408'),
(455,'Bib Gourmand','https://guide.michelin.com/us/en/nordrhein-westfalen/dusseldorf/restaurant/essbar'),
(456,'Bib Gourmand','https://guide.michelin.com/us/en/nordrhein-westfalen/dusseldorf/restaurant/munstermanns-kontor'),
(457,'Bib Gourmand','https://guide.michelin.com/us/en/nordrhein-westfalen/gummersbach/restaurant/muhlenhelle-bistro'),
(458,'Bib Gourmand','https://guide.michelin.com/us/en/nordrhein-westfalen/harsewinkel/restaurant/poppenborg-s-stubchen'),
(459,'Bib Gourmand','https://guide.michelin.com/us/en/nordrhein-westfalen/hvelhof/restaurant/gasthof-brink'),
(460,'Bib Gourmand','https://guide.michelin.com/us/en/nordrhein-westfalen/koln/restaurant/capricorn-i-aries-brasserie'),
(461,'Bib Gourmand','https://guide.michelin.com/us/en/nordrhein-westfalen/koln/restaurant/gasthaus-scherz'),
(462,'Bib Gourmand','https://guide.michelin.com/us/en/nordrhein-westfalen/koln/restaurant/henne-weinbar'),
(463,'Bib Gourmand','https://guide.michelin.com/us/en/nordrhein-westfalen/neukirchen-vluyn/restaurant/little-john-s'),
(464,'Bib Gourmand','https://guide.michelin.com/us/en/nordrhein-westfalen/vreden/restaurant/buschker-s-stuben'),
(465,'Bib Gourmand','https://guide.michelin.com/us/en/rheinland-pfalz/andernach/restaurant/ai-pero'),
(466,'Bib Gourmand','https://guide.michelin.com/us/en/rheinland-pfalz/bad-kreuznach/restaurant/im-kittchen'),
(467,'Bib Gourmand','https://guide.michelin.com/us/en/rheinland-pfalz/deidesheim/restaurant/gasthaus-zur-kanne'),
(468,'Bib Gourmand','https://guide.michelin.com/us/en/rheinland-pfalz/frankweiler/restaurant/weinstube-brand'),
(469,'Bib Gourmand','https://guide.michelin.com/us/en/rheinland-pfalz/freinsheim/restaurant/weinreich'),
(470,'Bib Gourmand','https://guide.michelin.com/us/en/rheinland-pfalz/geisfeld_1330179/restaurant/kaufmann-s'),
(471,'Bib Gourmand','https://guide.michelin.com/us/en/rheinland-pfalz/hardert/restaurant/corona-hotel-zur-post'),
(472,'Bib Gourmand','https://guide.michelin.com/us/en/rheinland-pfalz/jugenheim-in-rheinhessen/restaurant/weedenhof'),
(473,'Bib Gourmand','https://guide.michelin.com/us/en/rheinland-pfalz/meerfeld/restaurant/poststuben'),
(474,'Bib Gourmand','https://guide.michelin.com/us/en/rheinland-pfalz/neupotz/restaurant/gehrlein-s-hardtwald'),
(475,'Bib Gourmand','https://guide.michelin.com/us/en/rheinland-pfalz/neupotz/restaurant/zum-lamm'),
(476,'Bib Gourmand','https://guide.michelin.com/us/en/saarland/blieskastel/restaurant/landgenuss'),
(477,'Bib Gourmand','https://guide.michelin.com/us/en/sachsen/aue/restaurant/lotters-wirtschaft-tausendguldenstube'),
(478,'Bib Gourmand','https://guide.michelin.com/us/en/sachsen/dresden/restaurant/deli351464'),
(479,'Bib Gourmand','https://guide.michelin.com/us/en/sachsen/pirna/restaurant/felsenbirne'),
(480,'Bib Gourmand','https://guide.michelin.com/us/en/sachsen/wilthen/restaurant/erbgericht-tautewalde'),
(481,'Bib Gourmand','https://guide.michelin.com/us/en/schleswig-holstein/neuendorf-bei-wilster/restaurant/zum-duckerstieg'),
(482,'Bib Gourmand','https://guide.michelin.com/us/en/schleswig-holstein/tangstedt/restaurant/gutskuche'),
(483,'Bib Gourmand','https://guide.michelin.com/us/en/thuringen/nordhausen/restaurant/feine-speiseschenke')
  ) v(line, cat, url);
  IF fxmd5 <> '410643990798c2b5c310529b23944b4b' THEN RAISE EXCEPTION 'fixture values md5 % differs', fxmd5; END IF;
  IF jsonb_array_length(fxj) <> 483 THEN RAISE EXCEPTION 'fixture lines % (expected 483)', jsonb_array_length(fxj); END IF;

  -- 0a. Batch 13 is the promoted Germany batch, and the staged rows are the run-2 rows
  SELECT count(*) INTO x FROM ingest_batches
   WHERE id = 13 AND batch_key = 'michelin-2026-germany' AND status = 'promoted';
  IF x <> 1 THEN RAISE EXCEPTION 'batch 13 is not michelin-2026-germany / promoted'; END IF;
  SELECT count(*), md5(string_agg((r.validation->>'line')||'|'||r.verdict||'|'||coalesce(r.validation->>'venue_id','')||'|'||coalesce(r.validation->>'city_id',''), ',' ORDER BY (r.validation->>'line')::int))
    INTO x, fp FROM ingest_rows r WHERE r.batch_id = 13;
  IF x <> 483 OR fp <> 'b12707287e46942f4d5603d98001a4e3' THEN RAISE EXCEPTION 'batch 13 rows % / fingerprint % differ from stage run 2', x, fp; END IF;
  SELECT count(*) INTO x FROM ingest_rows r
    JOIN jsonb_to_recordset(fxj) f(line int, cat text, url text) ON f.line = (r.validation->>'line')::int
   WHERE r.batch_id = 13 AND (r.raw->>'source_url' IS DISTINCT FROM f.url OR r.raw->>'category' IS DISTINCT FROM f.cat
                              OR (r.raw->>'_line')::int <> f.line);
  IF x <> 0 THEN RAISE EXCEPTION 'staged rows that differ from the fixture: %', x; END IF;

  -- 1. Build the plan from live data
  SELECT jsonb_agg(to_jsonb(p) ORDER BY p.award_id), count(*),
         md5(string_agg(p.award_id||'|'||p.venue_id||'|'||p.category||'|'||p.url, E'\n' ORDER BY p.award_id))
    INTO plan, n_plan, fp
  FROM (
    SELECT (r.validation->'collides_with'->>0)::bigint AS award_id, r.validation->>'venue_id' AS venue_id,
           f.cat AS category, f.url, f.line,
           jsonb_array_length(r.validation->'collides_with') AS ncw, r.validation->>'reason' AS reason,
           a.venue_id AS a_venue, a.category AS a_cat, a.source_id AS a_src, a.year AS a_year,
           a.source_url AS a_url, a.rank AS a_rank, a.distinction AS a_dist, c.country_iso
      FROM ingest_rows r
      JOIN jsonb_to_recordset(fxj) f(line int, cat text, url text) ON f.line = (r.validation->>'line')::int
      LEFT JOIN awards a ON a.id = (r.validation->'collides_with'->>0)::bigint
      LEFT JOIN venues v ON v.id = a.venue_id
      LEFT JOIN cities c ON c.id = v.city_id
     WHERE r.batch_id = 13 AND r.verdict = 'duplicate'
  ) p;

  -- 2. Pre-checks
  IF n_plan <> 336 THEN RAISE EXCEPTION 'plan rows % (expected 336)', n_plan; END IF;
  IF fp <> 'ae4a8405d519950b8bbc3746578e3921' THEN RAISE EXCEPTION 'plan fingerprint % differs from the Oct 8 read', fp; END IF;
  SELECT md5(string_agg(q.award_id::text, ',' ORDER BY q.award_id)) INTO fp
    FROM jsonb_to_recordset(plan) q(award_id bigint);
  IF fp <> 'a107a3ac640e98b768f476f8bfe7852e' THEN RAISE EXCEPTION 'award id list md5 % differs', fp; END IF;
  SELECT count(DISTINCT q.award_id), count(DISTINCT q.url) INTO x, n
    FROM jsonb_to_recordset(plan) q(award_id bigint, url text);
  IF x <> 336 OR n <> 336 THEN RAISE EXCEPTION 'distinct ids % / urls % (expected 336 / 336)', x, n; END IF;

  -- 2a. Per-row test: one collision, it is this row, venue and category agree, Michelin 2026 legacy row in DE
  SELECT count(*) INTO x FROM jsonb_to_recordset(plan) q(award_id bigint, venue_id text, category text, ncw int,
           reason text, a_venue text, a_cat text, a_src text, a_year int, a_url text, a_rank int, a_dist text, country_iso text)
   WHERE NOT (q.ncw = 1 AND q.reason = 'duplicate_of_existing_award'
              AND q.a_venue = q.venue_id AND q.a_cat = q.category
              AND q.a_src = 'michelin' AND q.a_year = 2026
              AND q.a_url IS NULL AND q.a_rank IS NULL AND q.a_dist IS NULL
              AND q.country_iso = 'DE');
  IF x <> 0 THEN RAISE EXCEPTION 'plan rows that fail the per-row test: %', x; END IF;
  SELECT sum(CASE q.category WHEN 'Three Stars' THEN 1000000 WHEN 'Two Stars' THEN 10000 WHEN 'One Star' THEN 100 WHEN 'Bib Gourmand' THEN 1 ELSE 100000000 END)
    INTO x FROM jsonb_to_recordset(plan) q(category text);
  IF x <> 12497700 THEN RAISE EXCEPTION 'category count % (expected 12497700 = 12/47/277/0)', x; END IF;

  -- 2b. URL form and uniqueness
  SELECT count(*) INTO x FROM jsonb_to_recordset(plan) q(url text)
   WHERE q.url !~ '^https://guide\.michelin\.com/us/en/[^/]+/[^/]+/restaurant/[^/]+$';
  IF x <> 0 THEN RAISE EXCEPTION 'URLs not on a guide.michelin.com/us/en venue page: %', x; END IF;
  SELECT count(*) INTO x FROM awards a, jsonb_to_recordset(plan) q(url text) WHERE a.source_url = q.url;
  IF x <> 0 THEN RAISE EXCEPTION 'card URLs already on an award row: %', x; END IF;

  -- 2c. The rows left out = the 2 German legacy 2026 rows with no card (3578, 7349)
  SELECT count(*), md5(string_agg(a.id::text, ',' ORDER BY a.id)) INTO x, fp
    FROM awards a JOIN venues v ON v.id = a.venue_id JOIN cities c ON c.id = v.city_id
   WHERE c.country_iso = 'DE' AND a.source_id = 'michelin' AND a.year = 2026 AND a.source_url IS NULL
     AND a.id NOT IN (SELECT q.award_id FROM jsonb_to_recordset(plan) q(award_id bigint));
  IF x <> 2 OR fp <> md5('3578,7349') THEN RAISE EXCEPTION 'German 2026 rows outside the plan % (expected 3578, 7349)', x; END IF;

  -- 2d. Counts before
  SELECT count(*) INTO x FROM awards;                 IF x <> 22396 THEN RAISE EXCEPTION 'awards before % (expected 22396)', x; END IF;
  SELECT count(*) INTO x FROM awards WHERE source_id = 'michelin' AND year = 2026;
                                                      IF x <> 4806 THEN RAISE EXCEPTION 'Michelin 2026 before % (expected 4806)', x; END IF;
  SELECT count(*) INTO x FROM awards a JOIN venues v ON v.id = a.venue_id JOIN cities c ON c.id = v.city_id
   WHERE c.country_iso = 'DE' AND a.source_id = 'michelin' AND a.year = 2026 AND a.source_url IS NULL;
                                                      IF x <> 338 THEN RAISE EXCEPTION 'German 2026 unsourced before % (expected 338)', x; END IF;
  SELECT count(*) INTO x FROM venues;                 IF x <> 11224 THEN RAISE EXCEPTION 'venues before % (expected 11224)', x; END IF;
  SELECT count(*) INTO x FROM listings;               IF x <> 11224 THEN RAISE EXCEPTION 'listings before % (expected 11224)', x; END IF;
  SELECT count(*) INTO x FROM slugs;                  IF x <> 12323 THEN RAISE EXCEPTION 'slugs before % (expected 12323)', x; END IF;
  SELECT count(*) INTO x FROM price;                  IF x <> 7049 THEN RAISE EXCEPTION 'price before % (expected 7049)', x; END IF;
  SELECT count(*) INTO x FROM city_label_source;      IF x <> 23852 THEN RAISE EXCEPTION 'city labels before % (expected 23852)', x; END IF;
  SELECT count(*) INTO x FROM (SELECT venue_id FROM awards WHERE source_id = 'michelin'
                               GROUP BY venue_id, year, category HAVING count(*) > 1) d;
                                                      IF x <> 0 THEN RAISE EXCEPTION 'venues with two Michelin rows of one year and category before: %', x; END IF;
  SELECT count(*), max(id) INTO led_n, led_max FROM source_capture_ledger;
  IF led_n <> 67 OR led_max <> 89 THEN RAISE EXCEPTION 'ledger before % / max % (expected 67 / 89)', led_n, led_max; END IF;
  SELECT count(*), max(id) INTO aud_n, aud_max FROM audit_log;
  IF aud_n <> 104121 OR aud_max <> 107714 THEN RAISE EXCEPTION 'audit_log before % / max % (expected 104121 / 107714)', aud_n, aud_max; END IF;

  -- 3. Write
  UPDATE awards a SET source_url = q.url
    FROM jsonb_to_recordset(plan) q(award_id bigint, venue_id text, category text, url text)
   WHERE a.id = q.award_id AND a.venue_id = q.venue_id AND a.category = q.category
     AND a.source_id = 'michelin' AND a.year = 2026 AND a.source_url IS NULL;
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 336 THEN RAISE EXCEPTION 'award rows updated % (expected 336)', n; END IF;

  INSERT INTO source_capture_ledger (publisher, field_type, items, job)
  VALUES ('michelin', 'award', 336, job_txt);
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'ledger rows inserted % (expected 1)', n; END IF;

  -- 4. Post-checks
  SELECT count(*) INTO x FROM awards a, jsonb_to_recordset(plan) q(award_id bigint, url text)
   WHERE a.id = q.award_id AND a.source_url = q.url;
  IF x <> 336 THEN RAISE EXCEPTION 'rows with the planned URL after % (expected 336)', x; END IF;
  SELECT count(*) INTO x FROM awards;                 IF x <> 22396 THEN RAISE EXCEPTION 'awards count changed: %', x; END IF;
  SELECT count(*) INTO x FROM awards WHERE source_id = 'michelin' AND year = 2026;
                                                      IF x <> 4806 THEN RAISE EXCEPTION 'Michelin 2026 count changed: %', x; END IF;
  SELECT count(*), md5(string_agg(a.id::text, ',' ORDER BY a.id)) INTO x, fp
    FROM awards a JOIN venues v ON v.id = a.venue_id JOIN cities c ON c.id = v.city_id
   WHERE c.country_iso = 'DE' AND a.source_id = 'michelin' AND a.year = 2026 AND a.source_url IS NULL;
  IF x <> 2 OR fp <> md5('3578,7349') THEN RAISE EXCEPTION 'German 2026 unsourced after % (expected 3578, 7349)', x; END IF;
  SELECT count(*), count(DISTINCT a.source_url) INTO x, n
    FROM awards a JOIN venues v ON v.id = a.venue_id JOIN cities c ON c.id = v.city_id
   WHERE c.country_iso = 'DE' AND a.source_id = 'michelin' AND a.year = 2026
     AND a.source_url ~ '^https://guide\.michelin\.com/us/en/';
  IF x <> 483 OR n <> 483 THEN RAISE EXCEPTION 'German 2026 sourced rows / distinct URLs after % / % (expected 483 / 483)', x, n; END IF;
  SELECT count(*) INTO x FROM (SELECT venue_id FROM awards WHERE source_id = 'michelin'
                               GROUP BY venue_id, year, category HAVING count(*) > 1) d;
  IF x <> 0 THEN RAISE EXCEPTION 'venues with two Michelin rows of one year and category after: %', x; END IF;
  SELECT count(*) INTO x FROM venues;            IF x <> 11224 THEN RAISE EXCEPTION 'venues changed: %', x; END IF;
  SELECT count(*) INTO x FROM listings;          IF x <> 11224 THEN RAISE EXCEPTION 'listings changed: %', x; END IF;
  SELECT count(*) INTO x FROM slugs;             IF x <> 12323 THEN RAISE EXCEPTION 'slugs changed: %', x; END IF;
  SELECT count(*) INTO x FROM price;             IF x <> 7049 THEN RAISE EXCEPTION 'price changed: %', x; END IF;
  SELECT count(*) INTO x FROM city_label_source; IF x <> 23852 THEN RAISE EXCEPTION 'city labels changed: %', x; END IF;

  SELECT count(*) INTO x FROM source_capture_ledger;
  IF x <> 68 THEN RAISE EXCEPTION 'ledger after % (expected 68)', x; END IF;
  SELECT count(*) INTO x FROM source_capture_ledger
   WHERE id > led_max AND publisher = 'michelin' AND field_type = 'award' AND items = 336 AND job = job_txt;
  IF x <> 1 THEN RAISE EXCEPTION 'new ledger row not found'; END IF;

  SELECT count(*) INTO x FROM audit_log WHERE id > aud_max;
  IF x <> 336 THEN RAISE EXCEPTION 'audit rows this transaction % (expected 336)', x; END IF;
  SELECT count(*) INTO x FROM audit_log al, jsonb_to_recordset(plan) q(award_id bigint, url text)
   WHERE al.id > aud_max AND al.table_name = 'awards' AND al.action = 'UPDATE' AND al.row_pk = q.award_id::text
     AND al.old_row->>'source_url' IS NULL AND al.new_row->>'source_url' = q.url
     AND (SELECT count(*) FROM jsonb_object_keys(al.new_row) k
           WHERE al.old_row->k IS DISTINCT FROM al.new_row->k) = 1;
  IF x <> 336 THEN RAISE EXCEPTION 'audit rows that change only source_url % (expected 336)', x; END IF;
END
$do$;
COMMIT;
