-- source-url-michelin-2026-chengdu-legacy.sql
-- CompassEats, Oct 2 2026. Open item 1 of handoff-chengdu-2026-archive-promoted-2026-10-02:
-- Chengdu archive method test 1, step 2 of 3. Set source_url IN PLACE on the 25 correct
-- legacy Michelin 2026 Chengdu rows (Ben's decision 2 of Sep 28 and its 5 conditions).
-- Source: reports/chengdu-2026-archive-relay.jsonl (40 lines),
--   sha256 216ffff2ad2578356ec3bdf4518c6d38ef488fb51822e28ec333f73e095f5ffc.
--   The 40 relay values below are generated by script from that file (no retyping).
--   md5 guard of slug|distinction|price|url (sorted by slug, C order): 8521dfb5e643e7ed8fd1f878a64b6d2b
-- Venue basis: fixtures/ingest/michelin-2027-chengdu.csv + -decisions.csv (47 lines,
--   generated by script). md5 guard of line|slug|category|decision: eb780729aaf0bca8b5a6e8a07bab9909
-- Per-row test (read Oct 2): venue, category and price agree with the archive card.
--   23 rows pass on all three tests with the standard basis.
--   Row 4516 (The Hall ve_cec4b19f8b): no price row. DECISION OPTION A ASSUMED: the price
--     test uses audit_log 107181 (the legacy price $$$$ that went with row 4516 before the
--     Sep 28 move, deleted with Upper House). Card price ¥¥¥¥. Gated below.
--   Row 9788 (Shu Di Dang Gui ve_f6f3a8b280): no 2027 card, so no decisions-file basis.
--     DECISION OPTION A ASSUMED: venue test by loose name key (card name minus the branch
--     "(Wuhou)"), plus category and price. Gated below.
--   If Ben chooses B for a row, this file is rebuilt without that row.
-- Plan fingerprint (md5 of award_id|venue_id|category|archive_url, by award_id, newline),
--   read Oct 2: f49708600f3182d89f89f0a1b42b0574 (25 rows).
-- Write: 1 UPDATE (25 rows, source_url only) + 1 ledger row. Expected audit rows: 25
--   (trg_audit_awards, UPDATE). The ledger has no audit trigger and no note column, so the
--   note goes in `job` after the job key.
-- Dry run: send only the DO block through the Read connector. All pre-checks run, then the
--   block stops at the UPDATE with "read-only transaction".

BEGIN;
DO $do$
DECLARE
  relj     jsonb;
  rmd5     text;
  fxj      jsonb;
  fxmd5    text;
  plan     jsonb;
  n_plan   int;
  fp       text;
  n        int;
  x        int;
  aud_max  bigint;
  aud_n    bigint;
  led_max  bigint;
  led_n    bigint;
  job_txt  text := 'source-url:michelin-2026-chengdu-legacy | archive: web.archive.org/web/<14-digit ts>id_/ guide.michelin.com Chengdu venue pages, one URL per row | relay reports/chengdu-2026-archive-relay.jsonl sha256 216ffff2ad2578356ec3bdf4518c6d38ef488fb51822e28ec333f73e095f5ffc | original capture May 13 to June 1, 2026, sourced from archive';
BEGIN
  -- 0. Source values (generated from the repo files) and their guards
  SELECT jsonb_agg(jsonb_build_object('slug', slug, 'dist', dist, 'price', price, 'url', url,
           'name', name, 'ts', ts, 'edition', edition, 'awarded', awarded, 'captured', captured)),
         md5(string_agg(slug||'|'||dist||'|'||price||'|'||url, E'\n' ORDER BY slug COLLATE "C"))
    INTO relj, rmd5
  FROM (VALUES
('bai-nian-fen-zheng-niu-rou','Bib Gourmand','¥','https://web.archive.org/web/20250903040600id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/bai-nian-fen-zheng-niu-rou','Bai Nian Fen Zheng Niu Rou','20250903040600','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/bai-nian-fen-zheng-niu-rou'),
('chaimen-hui','One Star','¥¥¥¥','https://web.archive.org/web/20250905233141id_/https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/chaimen-hui','Chaimen Hui','20250905233141','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/chaimen-hui'),
('chen-mapo-tofu-qinghua-road','Bib Gourmand','¥','https://web.archive.org/web/20250907025940id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/chen-mapo-tofu-qinghua-road','Chen Mapo Tofu (Qinghua Road)','20250907025940','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/chen-mapo-tofu-qinghua-road'),
('co','One Star','¥¥¥¥','https://web.archive.org/web/20250905002324id_/https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/co','Co-','20250905002324','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/co'),
('cuo-xia','Bib Gourmand','¥¥','https://web.archive.org/web/20250905043720id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/cuo-xia','Cuo Xia','20250905043720','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/cuo-xia'),
('dumpling-drinks','Bib Gourmand','¥','https://web.archive.org/web/20250918143854id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/dumpling-drinks','Dumpling & Drinks (Lancao Road)','20250918143854','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/dumpling-drinks'),
('fang-xiang-jing','One Star','¥¥¥','https://web.archive.org/web/20250903083546id_/https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/fang-xiang-jing','Fang Xiang Jing','20250903083546','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/fang-xiang-jing'),
('fu-rong-huang','One Star','¥¥','https://web.archive.org/web/20250906061644id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/fu-rong-huang','Fu Rong Huang','20250906061644','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/fu-rong-huang'),
('gan-ji-fei-chang-fen','Bib Gourmand','¥','https://web.archive.org/web/20250906115008id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/gan-ji-fei-chang-fen','Gan Ji Fei Chang Fen (Jinniu)','20250906115008','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/gan-ji-fei-chang-fen'),
('gong-zhou-ba-shu-wei-yuan','Bib Gourmand','¥','https://web.archive.org/web/20250903123137id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/gong-zhou-ba-shu-wei-yuan','Gong Zhou · Ba Shu Wei Yuan','20250903123137','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/gong-zhou-ba-shu-wei-yuan'),
('guan-jin-wuhou','Bib Gourmand','¥¥','https://web.archive.org/web/20250905062938id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/guan-jin-wuhou','Guan Jin (Chenghan South Road)','20250905062938','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/guan-jin-wuhou'),
('hokkien-cuisine','One Star','¥¥¥','https://web.archive.org/web/20251014142919id_/https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/hokkien-cuisine','Hokkien Cuisine','20251014142919','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/hokkien-cuisine'),
('hu-er-ge-yao-shan-ti-hua','Bib Gourmand','¥','https://web.archive.org/web/20250903092640id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/hu-er-ge-yao-shan-ti-hua','Hu Er Ge Yao Shan Ti Hua','20250903092640','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/hu-er-ge-yao-shan-ti-hua'),
('lao-chengdu-san-yang-mian','Bib Gourmand','¥','https://web.archive.org/web/20250903162127id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/lao-chengdu-san-yang-mian','Lao Chengdu Yi Cheng Xian San Yang Mian','20250903162127','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/lao-chengdu-san-yang-mian'),
('long-sen-yuan','Bib Gourmand','¥¥','https://web.archive.org/web/20250904234406id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/long-sen-yuan','Long Sen Yuan (Qingyang)','20250904234406','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/long-sen-yuan'),
('ma-s-kitchen','One Star','¥¥','https://web.archive.org/web/20250903155613id_/https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/ma-s-kitchen','Ma''s Kitchen (Jinjiang)','20250903155613','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/ma-s-kitchen'),
('mi-xun-teahouse','One Star','¥¥','https://web.archive.org/web/20250906000413id_/https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/mi-xun-teahouse','Mi Xun Teahouse','20250906000413','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/mi-xun-teahouse'),
('mind','Bib Gourmand','¥','https://web.archive.org/web/20250903052819id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/mind','Mind','20250903052819','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/mind'),
('mosnack','Bib Gourmand','¥','https://web.archive.org/web/20250907144239id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/mosnack','Mosnack','20250907144239','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/mosnack'),
('nian-feng-restaurant','Bib Gourmand','¥¥','https://web.archive.org/web/20250906064909id_/https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/nian-feng-restaurant','Nian Feng Restaurant','20250906064909','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/nian-feng-restaurant'),
('organization-south','Bib Gourmand','¥¥','https://web.archive.org/web/20250904203139id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/organization-south','Organization South','20250904203139','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/organization-south'),
('rong-yuan-can-guan','Bib Gourmand','¥¥','https://web.archive.org/web/20250905113951id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/rong-yuan-can-guan','Rong Yuan Can Guan','20250905113951','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/rong-yuan-can-guan'),
('rongrong-beida-pugaimian','Bib Gourmand','¥','https://web.archive.org/web/20250919170420id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/rongrong-beida-pugaimian','Rongrong Beida Pugaimian','20250919170420','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/rongrong-beida-pugaimian'),
('shudidanggui','Bib Gourmand','¥¥','https://web.archive.org/web/20250915103016id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/shudidanggui','Shudidanggui (Wuhou)','20250915103016','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/shudidanggui'),
('silver-pot','One Star','¥¥¥','https://web.archive.org/web/20250910171504id_/https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/silver-pot','Silver Pot','20250910171504','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/silver-pot'),
('the-hall','One Star','¥¥¥¥','https://web.archive.org/web/20250921083429id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/the-hall','The Hall','20250921083429','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/the-hall'),
('the-woo-s','Bib Gourmand','¥¥','https://web.archive.org/web/20250903085400id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/the-woo-s','The Woo''s (Jinjiang)','20250903085400','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/the-woo-s'),
('ting-yuan-399','Bib Gourmand','¥¥','https://web.archive.org/web/20250905223723id_/https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/ting-yuan-399','Ting Yuan 399 (Jinjiang)','20250905223723','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/ting-yuan-399'),
('wan-san-mian-guan-jinjiang','Bib Gourmand','¥','https://web.archive.org/web/20250911003944id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/wan-san-mian-guan-jinjiang','Wan San Mian Guan (Qinglongzheng Street)','20250911003944','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/wan-san-mian-guan-jinjiang'),
('wu-ji-guai-wei-mian-jinjiang','Bib Gourmand','¥','https://web.archive.org/web/20250905064833id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/wu-ji-guai-wei-mian-jinjiang','Wu Ji Guai Wei Mian (Jinjiang)','20250905064833','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/wu-ji-guai-wei-mian-jinjiang'),
('xin-rong-ji-1207940','Two Stars','¥¥¥¥','https://web.archive.org/web/20250906145514id_/https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/xin-rong-ji-1207940','Xin Rong Ji','20250906145514','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/xin-rong-ji-1207940'),
('xu-s-cuisine','One Star','¥¥¥','https://web.archive.org/web/20250903183726id_/https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/xu-s-cuisine','Xu''s Cuisine','20250903183726','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/xu-s-cuisine'),
('yangboying-za-jiang-mian','Bib Gourmand','¥','https://web.archive.org/web/20250904055054id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/yangboying-za-jiang-mian','Yangboying Chuan Tong Za Jiang Mian','20250904055054','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/yangboying-za-jiang-mian'),
('yao-guai-mian','Bib Gourmand','¥','https://web.archive.org/web/20250903040814id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/yao-guai-mian','Yao Guai Mian','20250903040814','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/yao-guai-mian'),
('yongle-restaurant-wuhou','Bib Gourmand','¥','https://web.archive.org/web/20250903123404id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/yongle-restaurant-wuhou','Yongle Restaurant (Wuhou)','20250903123404','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/yongle-restaurant-wuhou'),
('young-art-yong-ya-he-xian-tongzilin-east-road','One Star','¥¥¥','https://web.archive.org/web/20260115030537id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/young-art-yong-ya-he-xian-tongzilin-east-road','Young Art · Yong Ya He Xian (Tongzilin East Road)','20260115030537','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/young-art-yong-ya-he-xian-tongzilin-east-road'),
('yu-zhi-lan-1196150','Two Stars','¥¥¥¥','https://web.archive.org/web/20250916042611id_/https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/yu-zhi-lan-1196150','Yu Zhi Lan','20250916042611','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/yu-zhi-lan-1196150'),
('zeng-niu-rou-qingyang','Bib Gourmand','¥','https://web.archive.org/web/20250925182743id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/zeng-niu-rou-qingyang','Zeng Niu Rou (Qingyang)','20250925182743','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/zeng-niu-rou-qingyang'),
('zhu-ji-zhi-mian-pu','Bib Gourmand','¥','https://web.archive.org/web/20250904212434id_/https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/zhu-ji-zhi-mian-pu','Zhu Ji Zhi Mian Pu (Jinjiang)','20250904212434','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/us/en/chengdu-municipality/chengdu/restaurant/zhu-ji-zhi-mian-pu'),
('zhuan-zhuan-hui-lianhua-south-road','Bib Gourmand','¥¥','https://web.archive.org/web/20250907034330id_/https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/zhuan-zhuan-hui-lianhua-south-road','Zhuan Zhuan Hui (Lianhua South Road)','20250907034330','2026 MICHELIN Guide Chengdu','2026','https://guide.michelin.com/en/chengdu-municipality/chengdu/restaurant/zhuan-zhuan-hui-lianhua-south-road')
  ) v(slug, dist, price, url, name, ts, edition, awarded, captured);
  IF rmd5 <> '8521dfb5e643e7ed8fd1f878a64b6d2b' THEN RAISE EXCEPTION 'relay values md5 % differs', rmd5; END IF;
  IF jsonb_array_length(relj) <> 40 THEN RAISE EXCEPTION 'relay lines % (expected 40)', jsonb_array_length(relj); END IF;

  SELECT jsonb_agg(jsonb_build_object('line', line, 'slug', slug, 'cat', cat, 'dec', dec)),
         md5(string_agg(line||'|'||slug||'|'||cat||'|'||dec, E'\n' ORDER BY line))
    INTO fxj, fxmd5
  FROM (VALUES
(1,'xin-rong-ji-1207940','Three Stars','new'),
(2,'yu-zhi-lan-1196150','Two Stars',''),
(3,'the-hall','One Star',''),
(4,'fang-xiang-jing','One Star','use:ve_e1109450cf'),
(5,'mi-xun-teahouse','One Star','use:ve_37910677a4'),
(6,'ma-s-kitchen','One Star',''),
(7,'xu-s-cuisine','One Star','use:ve_36ae4d6bcd'),
(8,'fu-rong-huang','One Star','use:ve_a3b31ca55d'),
(9,'young-art-yong-ya-he-xian-tongzilin-east-road','One Star','use:ve_db92193fc0'),
(10,'zinan','One Star',''),
(11,'silver-pot','One Star','use:ve_ad0bb34099'),
(12,'focus-by-bill-yue','One Star',''),
(13,'hokkien-cuisine','One Star',''),
(14,'co','One Star','use:ve_41a4101cbd'),
(15,'chaimen-hui','One Star','use:ve_d33390c047'),
(16,'no-37-lao-yuan-ba-chao-shou','Bib Gourmand',''),
(17,'yangboying-za-jiang-mian','Bib Gourmand','use:ve_9c004b1f6f'),
(18,'lao-chengdu-san-yang-mian','Bib Gourmand','use:ve_4f5d44401e'),
(19,'rongrong-beida-pugaimian','Bib Gourmand',''),
(20,'gan-ji-fei-chang-fen','Bib Gourmand','use:ve_a64a235506'),
(21,'mosnack','Bib Gourmand',''),
(22,'long-sen-yuan','Bib Gourmand','use:ve_7ab59d83eb'),
(23,'ban-tian-te-se-mian','Bib Gourmand',''),
(24,'bai-nian-fen-zheng-niu-rou','Bib Gourmand','use:ve_84dc39ab0e'),
(25,'gong-zhou-ba-shu-wei-yuan','Bib Gourmand','use:ve_820878c98e'),
(26,'wan-san-mian-guan-jinjiang','Bib Gourmand',''),
(27,'hu-er-ge-yao-shan-ti-hua','Bib Gourmand',''),
(28,'nian-feng-restaurant','Bib Gourmand','use:ve_69877791d1'),
(29,'wu-ji-guai-wei-mian-jinjiang','Bib Gourmand',''),
(30,'chen-mapo-tofu-qinghua-road','Bib Gourmand','use:ve_b8255461a4'),
(31,'the-woo-s','Bib Gourmand',''),
(32,'rong-yuan-can-guan','Bib Gourmand','use:ve_67f01b1cdf'),
(33,'gui-tian-yuan-zi','Bib Gourmand',''),
(34,'zhuan-zhuan-hui-lianhua-south-road','Bib Gourmand',''),
(35,'da-ya-ji','Bib Gourmand',''),
(36,'dumpling-drinks','Bib Gourmand',''),
(37,'yongle-restaurant-wuhou','Bib Gourmand',''),
(38,'zeng-niu-rou-qingyang','Bib Gourmand',''),
(39,'ren-ren-shui-jiao','Bib Gourmand',''),
(40,'mind','Bib Gourmand','use:ve_133ee0a10d'),
(41,'yao-guai-mian','Bib Gourmand',''),
(42,'ting-yuan-399','Bib Gourmand',''),
(43,'xiao-you-shao-mai-qiangyang','Bib Gourmand',''),
(44,'guan-jin-wuhou','Bib Gourmand',''),
(45,'organization-south','Bib Gourmand',''),
(46,'cuo-xia','Bib Gourmand',''),
(47,'mao-wu-da-jiu-dian','Bib Gourmand','')
  ) v(line, slug, cat, dec);
  IF fxmd5 <> 'eb780729aaf0bca8b5a6e8a07bab9909' THEN RAISE EXCEPTION '2027 file values md5 % differs', fxmd5; END IF;

  -- 1. Build the plan from live data
  SELECT jsonb_agg(to_jsonb(p) ORDER BY p.award_id), count(*),
         md5(string_agg(p.award_id||'|'||p.venue_id||'|'||p.category||'|'||p.url, E'\n' ORDER BY p.award_id))
    INTO plan, n_plan, fp
  FROM (
    SELECT m.award_id, m.venue_id, m.category, m.slug, m.method, m.slug27, m.n27, m.np, m.sym,
             r.url, r.dist, r.price, r.ts, r.edition, r.awarded, r.captured
      FROM (
        SELECT l.id AS award_id, l.venue_id, l.category, coalesce(y.slug27, nm.slug) AS slug,
               CASE WHEN y.slug27 IS NOT NULL THEN '2027 card' WHEN nm.slug IS NOT NULL THEN 'name' END AS method,
               y.slug27, y.n27,
               (SELECT count(*) FROM price p WHERE p.venue_id = l.venue_id) AS np,
               (SELECT min(p.symbol_raw) FROM price p WHERE p.venue_id = l.venue_id) AS sym
        FROM (SELECT a.id, a.venue_id, v.name, a.category FROM awards a JOIN venues v ON v.id = a.venue_id
              WHERE v.city_id = 'ci_354b500e3a' AND a.source_id = 'michelin' AND a.year = 2026
                AND a.source_url IS NULL) l
        LEFT JOIN (SELECT venue_id, min(split_part(source_url, '/restaurant/', 2)) AS slug27, count(*) AS n27
                   FROM awards WHERE source_id = 'michelin' AND year = 2027 GROUP BY venue_id) y
               ON y.venue_id = l.venue_id
        LEFT JOIN (SELECT l2.id, r2.slug
                   FROM (SELECT a.id, a.venue_id, v.name FROM awards a JOIN venues v ON v.id = a.venue_id
                         WHERE v.city_id = 'ci_354b500e3a' AND a.source_id = 'michelin' AND a.year = 2026
                           AND a.source_url IS NULL) l2
                   JOIN jsonb_to_recordset(relj) r2(slug text, name text)
                     ON (case when length(regexp_replace(regexp_replace(btrim(regexp_replace(lower(f_unaccent(l2.name)), '[^a-z0-9]+', ' ', 'g')), '^((restaurant|le|la|les|l|hotel)\s+)+', ''), '[^a-z0-9]+', '', 'g')) < 3 then null else regexp_replace(regexp_replace(btrim(regexp_replace(lower(f_unaccent(l2.name)), '[^a-z0-9]+', ' ', 'g')), '^((restaurant|le|la|les|l|hotel)\s+)+', ''), '[^a-z0-9]+', '', 'g') end) = (case when length(regexp_replace(regexp_replace(btrim(regexp_replace(lower(f_unaccent(regexp_replace(r2.name, '\s*\([^)]*\)$', ''))), '[^a-z0-9]+', ' ', 'g')), '^((restaurant|le|la|les|l|hotel)\s+)+', ''), '[^a-z0-9]+', '', 'g')) < 3 then null else regexp_replace(regexp_replace(btrim(regexp_replace(lower(f_unaccent(regexp_replace(r2.name, '\s*\([^)]*\)$', ''))), '[^a-z0-9]+', ' ', 'g')), '^((restaurant|le|la|les|l|hotel)\s+)+', ''), '[^a-z0-9]+', '', 'g') end)
                   WHERE NOT EXISTS (SELECT 1 FROM awards b WHERE b.venue_id = l2.venue_id
                                     AND b.source_id = 'michelin' AND b.year = 2027)) nm
               ON nm.id = l.id
      ) m
      JOIN jsonb_to_recordset(relj) r(slug text, dist text, price text, url text, name text, ts text,
                                      edition text, awarded text, captured text)
        ON r.slug = m.slug
  ) p;

  -- 2. Pre-checks
  IF n_plan <> 25 THEN RAISE EXCEPTION 'plan rows % (expected 25)', n_plan; END IF;
  IF fp <> 'f49708600f3182d89f89f0a1b42b0574' THEN RAISE EXCEPTION 'plan fingerprint % differs from the Oct 2 read', fp; END IF;
  SELECT count(DISTINCT q.award_id), count(DISTINCT q.url) INTO x, n
    FROM jsonb_to_recordset(plan) q(award_id bigint, url text);
  IF x <> 25 OR n <> 25 THEN RAISE EXCEPTION 'distinct ids % / urls % (expected 25 / 25)', x, n; END IF;

  -- 2a. Venue test
  SELECT count(*) INTO x FROM jsonb_to_recordset(plan) q(method text, n27 int)
   WHERE q.method = '2027 card' AND q.n27 <> 1;
  IF x <> 0 THEN RAISE EXCEPTION 'venues with more than one 2027 card: %', x; END IF;
  SELECT count(*) INTO x FROM jsonb_to_recordset(plan) q(venue_id text, slug27 text)
    JOIN jsonb_to_recordset(fxj) f(slug text, dec text) ON f.dec = 'use:'||q.venue_id
   WHERE f.slug IS DISTINCT FROM q.slug27;
  IF x <> 0 THEN RAISE EXCEPTION 'venue differs from the 2027 decisions file: %', x; END IF;
  SELECT count(*) INTO x FROM jsonb_to_recordset(plan) q(venue_id text)
    JOIN jsonb_to_recordset(fxj) f(dec text) ON f.dec = 'use:'||q.venue_id;
  IF x <> 18 THEN RAISE EXCEPTION 'plan rows with a 2027 use: decision % (expected 18)', x; END IF;
  SELECT count(*) INTO x FROM jsonb_to_recordset(plan) q(award_id bigint, venue_id text, method text)
   WHERE q.method = 'name' AND NOT (q.award_id = 9788 AND q.venue_id = 've_f6f3a8b280');
  IF x <> 0 THEN RAISE EXCEPTION 'name-only venue test outside row 9788: %', x; END IF;
  SELECT count(*) INTO x FROM jsonb_to_recordset(plan) q(method text) WHERE q.method = 'name';
  IF x <> 1 THEN RAISE EXCEPTION 'name-only rows % (expected 1, row 9788)', x; END IF;

  -- 2b. Category test
  SELECT count(*) INTO x FROM jsonb_to_recordset(plan) q(category text, dist text)
   WHERE q.category IS DISTINCT FROM q.dist;
  IF x <> 0 THEN RAISE EXCEPTION 'category differs from the archive card: %', x; END IF;

  -- 2c. Price test
  SELECT count(*) INTO x FROM jsonb_to_recordset(plan) q(np int, sym text, price text)
   WHERE q.np = 1 AND NOT (q.sym ~ '^\$+$' AND char_length(q.sym) = char_length(q.price));
  IF x <> 0 THEN RAISE EXCEPTION 'price differs from the archive card: %', x; END IF;
  SELECT count(*) INTO x FROM jsonb_to_recordset(plan) q(award_id bigint, np int)
   WHERE q.np <> 1 AND NOT (q.award_id = 4516 AND q.np = 0);
  IF x <> 0 THEN RAISE EXCEPTION 'rows with no single price, other than 4516: %', x; END IF;
  -- Row 4516: the price that went with the row before the Sep 28 move (audit 107181)
  SELECT count(*) INTO x FROM audit_log al
   WHERE al.id = 107181 AND al.table_name = 'price' AND al.action = 'DELETE'
     AND al.old_row->>'venue_id' = 've_7b747b10ea' AND al.old_row->>'symbol_raw' = '$$$$';
  IF x <> 1 THEN RAISE EXCEPTION 'audit 107181 price evidence for row 4516 not found'; END IF;
  SELECT count(*) INTO x FROM audit_log al
   WHERE al.id = 107178 AND al.table_name = 'awards' AND al.action = 'UPDATE' AND al.row_pk = '4516'
     AND al.old_row->>'venue_id' = 've_7b747b10ea' AND al.new_row->>'venue_id' = 've_cec4b19f8b';
  IF x <> 1 THEN RAISE EXCEPTION 'audit 107178 move of row 4516 not found'; END IF;
  SELECT count(*) INTO x FROM jsonb_to_recordset(plan) q(award_id bigint, price text)
   WHERE q.award_id = 4516 AND q.price = '¥¥¥¥';
  IF x <> 1 THEN RAISE EXCEPTION 'row 4516 card price is not 4 symbols'; END IF;

  -- 2d. Ruling conditions 1 to 4 and 7 on each stored URL
  SELECT count(*) INTO x FROM jsonb_to_recordset(plan) q(url text, ts text, edition text, awarded text, captured text)
   WHERE NOT (q.url ~ '^https://web\.archive\.org/web/\d{14}id_/https://guide\.michelin\.com/[a-z]{2}(/[a-z]{2})?/chengdu-municipality/chengdu/restaurant/'
              AND substr(q.url, 29, 14) = q.ts AND substr(q.url, 47) = q.captured
              AND q.ts >= '20250903000000' AND q.ts < '20260902000000'
              AND q.edition = '2026 MICHELIN Guide Chengdu' AND q.awarded = '2026');
  IF x <> 0 THEN RAISE EXCEPTION 'URLs that fail ruling conditions 1-4/7: %', x; END IF;
  SELECT count(*) INTO x FROM awards a, jsonb_to_recordset(plan) q(url text) WHERE a.source_url = q.url;
  IF x <> 0 THEN RAISE EXCEPTION 'archive URLs already on an award row: %', x; END IF;

  -- 2e. The rows left out = the 7 held venues (Sep 28 list)
  SELECT count(*), md5(string_agg(a.id::text, ',' ORDER BY a.id)) INTO x, fp
    FROM awards a JOIN venues v ON v.id = a.venue_id
   WHERE v.city_id = 'ci_354b500e3a' AND a.source_id = 'michelin' AND a.year = 2026 AND a.source_url IS NULL
     AND a.id NOT IN (SELECT q.award_id FROM jsonb_to_recordset(plan) q(award_id bigint));
  IF x <> 7 OR fp <> 'bcc44f12bc65c96bb5bed543ecdb668b' THEN RAISE EXCEPTION 'rows outside the plan % (expected the 7 held rows)', x; END IF;

  -- 2f. Counts before
  SELECT count(*) INTO x FROM awards;                 IF x <> 22256 THEN RAISE EXCEPTION 'awards before % (expected 22256)', x; END IF;
  SELECT count(*) INTO x FROM awards WHERE source_id = 'michelin' AND year = 2026;
                                                      IF x <> 4666 THEN RAISE EXCEPTION 'Michelin 2026 before % (expected 4666)', x; END IF;
  SELECT count(*) INTO x FROM awards a JOIN venues v ON v.id = a.venue_id
   WHERE v.city_id = 'ci_354b500e3a' AND a.source_id = 'michelin' AND a.year = 2026;
                                                      IF x <> 47 THEN RAISE EXCEPTION 'Chengdu 2026 rows before % (expected 47)', x; END IF;
  SELECT count(*) INTO x FROM venues;                 IF x <> 11212 THEN RAISE EXCEPTION 'venues before % (expected 11212)', x; END IF;
  SELECT count(*) INTO x FROM listings;               IF x <> 11212 THEN RAISE EXCEPTION 'listings before % (expected 11212)', x; END IF;
  SELECT count(*) INTO x FROM slugs;                  IF x <> 12311 THEN RAISE EXCEPTION 'slugs before % (expected 12311)', x; END IF;
  SELECT count(*) INTO x FROM price;                  IF x <> 7056 THEN RAISE EXCEPTION 'price before % (expected 7056)', x; END IF;
  SELECT count(*) INTO x FROM city_label_source;      IF x <> 23828 THEN RAISE EXCEPTION 'city labels before % (expected 23828)', x; END IF;
  SELECT count(*) INTO x FROM (SELECT venue_id FROM awards WHERE source_id = 'michelin' AND year = 2026
                               GROUP BY venue_id, category HAVING count(*) > 1) d;
                                                      IF x <> 0 THEN RAISE EXCEPTION 'venues with two Michelin 2026 rows before: %', x; END IF;
  SELECT count(*), max(id) INTO led_n, led_max FROM source_capture_ledger;
  IF led_n <> 63 OR led_max <> 83 THEN RAISE EXCEPTION 'ledger before % / max % (expected 63 / 83)', led_n, led_max; END IF;
  SELECT count(*), max(id) INTO aud_n, aud_max FROM audit_log;
  IF aud_n <> 103831 OR aud_max <> 107220 THEN RAISE EXCEPTION 'audit_log before % / max % (expected 103831 / 107220)', aud_n, aud_max; END IF;

  -- 3. Write
  UPDATE awards a SET source_url = q.url
    FROM jsonb_to_recordset(plan) q(award_id bigint, venue_id text, category text, url text)
   WHERE a.id = q.award_id AND a.venue_id = q.venue_id AND a.category = q.category
     AND a.source_id = 'michelin' AND a.year = 2026 AND a.source_url IS NULL;
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 25 THEN RAISE EXCEPTION 'award rows updated % (expected 25)', n; END IF;

  INSERT INTO source_capture_ledger (publisher, field_type, items, job)
  VALUES ('michelin', 'award', 25, job_txt);
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'ledger rows inserted % (expected 1)', n; END IF;

  -- 4. Post-checks
  SELECT count(*) INTO x FROM awards a, jsonb_to_recordset(plan) q(award_id bigint, url text)
   WHERE a.id = q.award_id AND a.source_url = q.url;
  IF x <> 25 THEN RAISE EXCEPTION 'rows with the planned URL after % (expected 25)', x; END IF;
  SELECT count(*) INTO x FROM awards;                 IF x <> 22256 THEN RAISE EXCEPTION 'awards count changed: %', x; END IF;
  SELECT count(*) INTO x FROM awards WHERE source_id = 'michelin' AND year = 2026;
                                                      IF x <> 4666 THEN RAISE EXCEPTION 'Michelin 2026 count changed: %', x; END IF;
  SELECT count(*), md5(string_agg(a.id::text, ',' ORDER BY a.id)) INTO x, fp
    FROM awards a JOIN venues v ON v.id = a.venue_id
   WHERE v.city_id = 'ci_354b500e3a' AND a.source_id = 'michelin' AND a.year = 2026 AND a.source_url IS NULL;
  IF x <> 7 OR fp <> 'bcc44f12bc65c96bb5bed543ecdb668b' THEN RAISE EXCEPTION 'Chengdu 2026 unsourced after % (expected the 7 held rows)', x; END IF;
  SELECT count(*), count(DISTINCT a.source_url) INTO x, n FROM awards a JOIN venues v ON v.id = a.venue_id
   WHERE v.city_id = 'ci_354b500e3a' AND a.source_id = 'michelin' AND a.year = 2026
     AND a.source_url ~ '^https://web\.archive\.org/web/\d{14}id_/https://guide\.michelin\.com/';
  IF x <> 40 OR n <> 40 THEN RAISE EXCEPTION 'Chengdu 2026 archive rows / distinct URLs after % / % (expected 40 / 40)', x, n; END IF;
  SELECT count(*) INTO x FROM (SELECT venue_id FROM awards WHERE source_id = 'michelin' AND year = 2026
                               GROUP BY venue_id, category HAVING count(*) > 1) d;
  IF x <> 0 THEN RAISE EXCEPTION 'venues with two Michelin 2026 rows after: %', x; END IF;
  SELECT count(*) INTO x FROM venues;            IF x <> 11212 THEN RAISE EXCEPTION 'venues changed: %', x; END IF;
  SELECT count(*) INTO x FROM listings;          IF x <> 11212 THEN RAISE EXCEPTION 'listings changed: %', x; END IF;
  SELECT count(*) INTO x FROM slugs;             IF x <> 12311 THEN RAISE EXCEPTION 'slugs changed: %', x; END IF;
  SELECT count(*) INTO x FROM price;             IF x <> 7056 THEN RAISE EXCEPTION 'price changed: %', x; END IF;
  SELECT count(*) INTO x FROM city_label_source; IF x <> 23828 THEN RAISE EXCEPTION 'city labels changed: %', x; END IF;

  SELECT count(*) INTO x FROM source_capture_ledger;
  IF x <> 64 THEN RAISE EXCEPTION 'ledger after % (expected 64)', x; END IF;
  SELECT count(*) INTO x FROM source_capture_ledger
   WHERE id > led_max AND publisher = 'michelin' AND field_type = 'award' AND items = 25 AND job = job_txt;
  IF x <> 1 THEN RAISE EXCEPTION 'new ledger row not found'; END IF;

  SELECT count(*) INTO x FROM audit_log WHERE id > aud_max;
  IF x <> 25 THEN RAISE EXCEPTION 'audit rows this transaction % (expected 25)', x; END IF;
  SELECT count(*) INTO x FROM audit_log al, jsonb_to_recordset(plan) q(award_id bigint, url text)
   WHERE al.id > aud_max AND al.table_name = 'awards' AND al.action = 'UPDATE' AND al.row_pk = q.award_id::text
     AND al.old_row->>'source_url' IS NULL AND al.new_row->>'source_url' = q.url
     AND (SELECT count(*) FROM jsonb_object_keys(al.new_row) k
           WHERE al.old_row->k IS DISTINCT FROM al.new_row->k) = 1;
  IF x <> 25 THEN RAISE EXCEPTION 'audit rows that change only source_url % (expected 25)', x; END IF;
END
$do$;
COMMIT;
