/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitySlugRouteImport } from './routes/city.$slug'
import { Route as ApiTopRestaurantsRouteImport } from './routes/api/top-restaurants'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugRoute = CitySlugRouteImport.update({
  id: '/city/$slug',
  path: '/city/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTopRestaurantsRoute = ApiTopRestaurantsRouteImport.update({
  id: '/api/top-restaurants',
  path: '/api/top-restaurants',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/top-restaurants': typeof ApiTopRestaurantsRoute
  '/city/$slug': typeof CitySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/top-restaurants': typeof ApiTopRestaurantsRoute
  '/city/$slug': typeof CitySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/top-restaurants': typeof ApiTopRestaurantsRoute
  '/city/$slug': typeof CitySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/top-restaurants' | '/city/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/top-restaurants' | '/city/$slug'
  id: '__root__' | '/' | '/api/top-restaurants' | '/city/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTopRestaurantsRoute: typeof ApiTopRestaurantsRoute
  CitySlugRoute: typeof CitySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$slug': {
      id: '/city/$slug'
      path: '/city/$slug'
      fullPath: '/city/$slug'
      preLoaderRoute: typeof CitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/top-restaurants': {
      id: '/api/top-restaurants'
      path: '/api/top-restaurants'
      fullPath: '/api/top-restaurants'
      preLoaderRoute: typeof ApiTopRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTopRestaurantsRoute: ApiTopRestaurantsRoute,
  CitySlugRoute: CitySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
