/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitySlugRouteImport } from './routes/city.$slug'
import { Route as AwardAwardRouteImport } from './routes/award/$award'
import { Route as ApiTopRestaurantsRouteImport } from './routes/api/top-restaurants'
import { Route as VenueCitySlugRouteImport } from './routes/venue/$city/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugRoute = CitySlugRouteImport.update({
  id: '/city/$slug',
  path: '/city/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardAwardRoute = AwardAwardRouteImport.update({
  id: '/award/$award',
  path: '/award/$award',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTopRestaurantsRoute = ApiTopRestaurantsRouteImport.update({
  id: '/api/top-restaurants',
  path: '/api/top-restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueCitySlugRoute = VenueCitySlugRouteImport.update({
  id: '/venue/$city/$slug',
  path: '/venue/$city/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/top-restaurants': typeof ApiTopRestaurantsRoute
  '/award/$award': typeof AwardAwardRoute
  '/city/$slug': typeof CitySlugRoute
  '/venue/$city/$slug': typeof VenueCitySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/top-restaurants': typeof ApiTopRestaurantsRoute
  '/award/$award': typeof AwardAwardRoute
  '/city/$slug': typeof CitySlugRoute
  '/venue/$city/$slug': typeof VenueCitySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/top-restaurants': typeof ApiTopRestaurantsRoute
  '/award/$award': typeof AwardAwardRoute
  '/city/$slug': typeof CitySlugRoute
  '/venue/$city/$slug': typeof VenueCitySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/top-restaurants'
    | '/award/$award'
    | '/city/$slug'
    | '/venue/$city/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/top-restaurants'
    | '/award/$award'
    | '/city/$slug'
    | '/venue/$city/$slug'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/top-restaurants'
    | '/award/$award'
    | '/city/$slug'
    | '/venue/$city/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiTopRestaurantsRoute: typeof ApiTopRestaurantsRoute
  AwardAwardRoute: typeof AwardAwardRoute
  CitySlugRoute: typeof CitySlugRoute
  VenueCitySlugRoute: typeof VenueCitySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$slug': {
      id: '/city/$slug'
      path: '/city/$slug'
      fullPath: '/city/$slug'
      preLoaderRoute: typeof CitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/award/$award': {
      id: '/award/$award'
      path: '/award/$award'
      fullPath: '/award/$award'
      preLoaderRoute: typeof AwardAwardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/top-restaurants': {
      id: '/api/top-restaurants'
      path: '/api/top-restaurants'
      fullPath: '/api/top-restaurants'
      preLoaderRoute: typeof ApiTopRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue/$city/$slug': {
      id: '/venue/$city/$slug'
      path: '/venue/$city/$slug'
      fullPath: '/venue/$city/$slug'
      preLoaderRoute: typeof VenueCitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiTopRestaurantsRoute: ApiTopRestaurantsRoute,
  AwardAwardRoute: AwardAwardRoute,
  CitySlugRoute: CitySlugRoute,
  VenueCitySlugRoute: VenueCitySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
