/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RegionsRouteImport } from './routes/regions'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnchartedSlugRouteImport } from './routes/uncharted/$slug'
import { Route as RegionSlugRouteImport } from './routes/region.$slug'
import { Route as CountrySlugRouteImport } from './routes/country.$slug'
import { Route as CitySlugRouteImport } from './routes/city.$slug'
import { Route as AwardAwardRouteImport } from './routes/award/$award'
import { Route as VenueCitySlugRouteImport } from './routes/venue/$city/$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsRoute = RegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnchartedSlugRoute = UnchartedSlugRouteImport.update({
  id: '/uncharted/$slug',
  path: '/uncharted/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionSlugRoute = RegionSlugRouteImport.update({
  id: '/region/$slug',
  path: '/region/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CountrySlugRoute = CountrySlugRouteImport.update({
  id: '/country/$slug',
  path: '/country/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugRoute = CitySlugRouteImport.update({
  id: '/city/$slug',
  path: '/city/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardAwardRoute = AwardAwardRouteImport.update({
  id: '/award/$award',
  path: '/award/$award',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueCitySlugRoute = VenueCitySlugRouteImport.update({
  id: '/venue/$city/$slug',
  path: '/venue/$city/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cities': typeof CitiesRoute
  '/contact': typeof ContactRoute
  '/guides': typeof GuidesRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/regions': typeof RegionsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/award/$award': typeof AwardAwardRoute
  '/city/$slug': typeof CitySlugRoute
  '/country/$slug': typeof CountrySlugRoute
  '/region/$slug': typeof RegionSlugRoute
  '/uncharted/$slug': typeof UnchartedSlugRoute
  '/venue/$city/$slug': typeof VenueCitySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cities': typeof CitiesRoute
  '/contact': typeof ContactRoute
  '/guides': typeof GuidesRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/regions': typeof RegionsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/award/$award': typeof AwardAwardRoute
  '/city/$slug': typeof CitySlugRoute
  '/country/$slug': typeof CountrySlugRoute
  '/region/$slug': typeof RegionSlugRoute
  '/uncharted/$slug': typeof UnchartedSlugRoute
  '/venue/$city/$slug': typeof VenueCitySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cities': typeof CitiesRoute
  '/contact': typeof ContactRoute
  '/guides': typeof GuidesRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/regions': typeof RegionsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/award/$award': typeof AwardAwardRoute
  '/city/$slug': typeof CitySlugRoute
  '/country/$slug': typeof CountrySlugRoute
  '/region/$slug': typeof RegionSlugRoute
  '/uncharted/$slug': typeof UnchartedSlugRoute
  '/venue/$city/$slug': typeof VenueCitySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cities'
    | '/contact'
    | '/guides'
    | '/methodology'
    | '/privacy'
    | '/regions'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/award/$award'
    | '/city/$slug'
    | '/country/$slug'
    | '/region/$slug'
    | '/uncharted/$slug'
    | '/venue/$city/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cities'
    | '/contact'
    | '/guides'
    | '/methodology'
    | '/privacy'
    | '/regions'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/award/$award'
    | '/city/$slug'
    | '/country/$slug'
    | '/region/$slug'
    | '/uncharted/$slug'
    | '/venue/$city/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cities'
    | '/contact'
    | '/guides'
    | '/methodology'
    | '/privacy'
    | '/regions'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/award/$award'
    | '/city/$slug'
    | '/country/$slug'
    | '/region/$slug'
    | '/uncharted/$slug'
    | '/venue/$city/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CitiesRoute: typeof CitiesRoute
  ContactRoute: typeof ContactRoute
  GuidesRoute: typeof GuidesRoute
  MethodologyRoute: typeof MethodologyRoute
  PrivacyRoute: typeof PrivacyRoute
  RegionsRoute: typeof RegionsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AwardAwardRoute: typeof AwardAwardRoute
  CitySlugRoute: typeof CitySlugRoute
  CountrySlugRoute: typeof CountrySlugRoute
  RegionSlugRoute: typeof RegionSlugRoute
  UnchartedSlugRoute: typeof UnchartedSlugRoute
  VenueCitySlugRoute: typeof VenueCitySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions': {
      id: '/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof RegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uncharted/$slug': {
      id: '/uncharted/$slug'
      path: '/uncharted/$slug'
      fullPath: '/uncharted/$slug'
      preLoaderRoute: typeof UnchartedSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region/$slug': {
      id: '/region/$slug'
      path: '/region/$slug'
      fullPath: '/region/$slug'
      preLoaderRoute: typeof RegionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/$slug': {
      id: '/country/$slug'
      path: '/country/$slug'
      fullPath: '/country/$slug'
      preLoaderRoute: typeof CountrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$slug': {
      id: '/city/$slug'
      path: '/city/$slug'
      fullPath: '/city/$slug'
      preLoaderRoute: typeof CitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/award/$award': {
      id: '/award/$award'
      path: '/award/$award'
      fullPath: '/award/$award'
      preLoaderRoute: typeof AwardAwardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue/$city/$slug': {
      id: '/venue/$city/$slug'
      path: '/venue/$city/$slug'
      fullPath: '/venue/$city/$slug'
      preLoaderRoute: typeof VenueCitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CitiesRoute: CitiesRoute,
  ContactRoute: ContactRoute,
  GuidesRoute: GuidesRoute,
  MethodologyRoute: MethodologyRoute,
  PrivacyRoute: PrivacyRoute,
  RegionsRoute: RegionsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AwardAwardRoute: AwardAwardRoute,
  CitySlugRoute: CitySlugRoute,
  CountrySlugRoute: CountrySlugRoute,
  RegionSlugRoute: RegionSlugRoute,
  UnchartedSlugRoute: UnchartedSlugRoute,
  VenueCitySlugRoute: VenueCitySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
